"""
50 diverse demo restaurants + script to append missing rows to an existing DB.

- `from seed_restaurants import RESTAURANTS` — used by seed.py on a fresh database.
- Run: `python seed_restaurants.py` — adds any restaurants from RESTAURANTS whose
  names are not already in the database (keeps your existing data).
"""

import models

_DEFAULT_HOURS = {
    "Monday": "11am-10pm",
    "Tuesday": "11am-10pm",
    "Wednesday": "11am-10pm",
    "Thursday": "11am-10pm",
    "Friday": "11am-11pm",
    "Saturday": "10am-11pm",
    "Sunday": "10am-9pm",
}

P1, P2, P3, P4 = (
    models.PriceTier.one,
    models.PriceTier.two,
    models.PriceTier.three,
    models.PriceTier.four,
)


def _h(**kwargs):
    return {**_DEFAULT_HOURS, **kwargs}


# ── 50 restaurants: varied cuisines, cities, price, keywords for AI / search ──
RESTAURANTS = [
    # --- Italian & Mediterranean ---
    dict(
        name="Tony's Little Italy",
        cuisine_type="Italian",
        address="1800 Washington St",
        city="San Francisco",
        state="CA",
        zip_code="94109",
        description="Authentic Italian cuisine with homemade pasta and a cozy atmosphere. Family-owned since 1987.",
        phone="(415) 555-0101",
        price_tier=P2,
        amenities=["WiFi", "Reservations", "Family-friendly"],
        keywords=["pasta", "pizza", "romantic", "wine"],
        hours=_h(),
    ),
    dict(
        name="Osteria Luna",
        cuisine_type="Italian",
        address="244 Valencia St",
        city="San Francisco",
        state="CA",
        zip_code="94103",
        description="Candlelit tables, handmade gnocchi, and an all-Italian wine list. Ideal for anniversaries.",
        phone="(415) 555-0102",
        price_tier=P3,
        amenities=["Reservations", "Wine bar", "Romantic"],
        keywords=["romantic", "fine dining", "date night", "upscale"],
        hours=_h(),
    ),
    dict(
        name="Mare Blu",
        cuisine_type="Mediterranean",
        address="900 North Point St",
        city="San Francisco",
        state="CA",
        zip_code="94109",
        description="Seafood-forward Mediterranean plates with harbor views and grilled octopus.",
        phone="(415) 555-0103",
        price_tier=P3,
        amenities=["Waterfront", "Reservations", "Full bar"],
        keywords=["seafood", "romantic", "view", "fine dining"],
        hours=_h(),
    ),
    # --- Mexican & Latin ---
    dict(
        name="El Farolito",
        cuisine_type="Mexican",
        address="2779 Mission St",
        city="San Francisco",
        state="CA",
        zip_code="94110",
        description="Late-night Mission District taqueria famous for oversized burritos and street tacos.",
        phone="(415) 555-0201",
        price_tier=P1,
        amenities=["Takeout", "Family-friendly"],
        keywords=["tacos", "burritos", "late night", "cheap eats"],
        hours=_h(Friday="10am-3am", Saturday="10am-3am"),
    ),
    dict(
        name="Cielito Lindo Plantas",
        cuisine_type="Mexican",
        address="3120 24th St",
        city="San Francisco",
        state="CA",
        zip_code="94110",
        description="Plant-based Mexican kitchen: jackfruit carnitas, cashew queso, and vegan tres leches for dessert.",
        phone="(415) 555-0202",
        price_tier=P2,
        amenities=["Vegan", "Outdoor Seating", "Takeout"],
        keywords=["vegan", "Mexican", "sweet", "dessert", "gluten-free"],
        hours=_h(),
    ),
    dict(
        name="Café de Olla",
        cuisine_type="Mexican",
        address="1800 Polk St",
        city="San Francisco",
        state="CA",
        zip_code="94109",
        description="Traditional mole, café de olla, and churros with chocolate dipping sauce.",
        phone="(415) 555-0203",
        price_tier=P2,
        amenities=["Brunch", "Coffee", "Dessert"],
        keywords=["sweet", "dessert", "coffee", "romantic", "brunch"],
        hours=_h(Saturday="9am-10pm", Sunday="9am-9pm"),
    ),
    # --- Asian ---
    dict(
        name="Dragon Palace",
        cuisine_type="Chinese",
        address="640 Jackson St",
        city="San Francisco",
        state="CA",
        zip_code="94133",
        description="Traditional Cantonese dim sum and seafood. Chinatown institution for over 30 years.",
        phone="(415) 555-0301",
        price_tier=P2,
        amenities=["Takeout", "Family-friendly", "Parking"],
        keywords=["dim sum", "seafood", "family"],
        hours=_h(),
    ),
    dict(
        name="Sakura Sushi",
        cuisine_type="Japanese",
        address="2001 Union St",
        city="San Francisco",
        state="CA",
        zip_code="94123",
        description="Premium omakase and à la carte sushi. Fresh fish flown in daily.",
        phone="(415) 555-0302",
        price_tier=P3,
        amenities=["Reservations", "Bar", "WiFi"],
        keywords=["sushi", "omakase", "date night", "fine dining"],
        hours=_h(Monday="Closed"),
    ),
    dict(
        name="Kin Khao",
        cuisine_type="Thai",
        address="55 Cyril Magnin St",
        city="San Francisco",
        state="CA",
        zip_code="94102",
        description="Bold Thai flavors, spicy curries, and mango sticky rice for a sweet finish.",
        phone="(415) 555-0303",
        price_tier=P2,
        amenities=["Takeout", "Spicy", "Dessert"],
        keywords=["Thai", "sweet", "spicy", "casual"],
        hours=_h(),
    ),
    dict(
        name="Lotus Leaf Vietnamese",
        cuisine_type="Vietnamese",
        address="731 Larkin St",
        city="San Francisco",
        state="CA",
        zip_code="94109",
        description="Pho, banh mi, and fresh herb plates. Light, bright space.",
        phone="(415) 555-0304",
        price_tier=P1,
        amenities=["Takeout", "Casual"],
        keywords=["pho", "healthy", "cheap eats"],
        hours=_h(),
    ),
    dict(
        name="Seoul Kitchen",
        cuisine_type="Korean",
        address="2200 Irving St",
        city="San Francisco",
        state="CA",
        zip_code="94122",
        description="Korean BBQ at the table, banchan parade, and soju cocktails.",
        phone="(415) 555-0305",
        price_tier=P2,
        amenities=["BBQ tables", "Bar", "Group-friendly"],
        keywords=["Korean BBQ", "late night", "fun"],
        hours=_h(),
    ),
    dict(
        name="Spice Route India",
        cuisine_type="Indian",
        address="1634 Haight St",
        city="San Francisco",
        state="CA",
        zip_code="94117",
        description="Regional curries, tandoor breads, and vegan thali nights every Thursday.",
        phone="(415) 555-0306",
        price_tier=P2,
        amenities=["Vegetarian options", "Reservations"],
        keywords=["Indian", "vegan", "spicy", "family"],
        hours=_h(),
    ),
    # --- American & brunch ---
    dict(
        name="Fog City Diner",
        cuisine_type="American",
        address="1300 Battery St",
        city="San Francisco",
        state="CA",
        zip_code="94111",
        description="Classic diner with burgers, shakes, and all-day breakfast.",
        phone="(415) 555-0401",
        price_tier=P2,
        amenities=["Bar", "Family-friendly", "WiFi"],
        keywords=["burgers", "brunch", "sweet", "milkshakes", "comfort food"],
        hours=_h(),
    ),
    dict(
        name="Nopa",
        cuisine_type="American",
        address="560 Divisadero St",
        city="San Francisco",
        state="CA",
        zip_code="94117",
        description="Farm-to-table in a stunning space. Cocktails and wood-fired dishes.",
        phone="(415) 555-0402",
        price_tier=P3,
        amenities=["Bar", "Reservations", "Outdoor Seating"],
        keywords=["farm-to-table", "cocktails", "date night", "upscale"],
        hours=_h(),
    ),
    dict(
        name="Ember & Oak Steakhouse",
        cuisine_type="American",
        address="252 California St",
        city="San Francisco",
        state="CA",
        zip_code="94111",
        description="Dry-aged steaks, truffle sides, and a deep wine cellar. Jacket-friendly fine dining.",
        phone="(415) 555-0403",
        price_tier=P4,
        amenities=["Fine dining", "Private dining", "Wine cellar"],
        keywords=["fine dining", "romantic", "steakhouse", "special occasion"],
        hours=_h(Sunday="5pm-10pm"),
    ),
    # --- Vegan & healthy ---
    dict(
        name="The Green Bowl",
        cuisine_type="Vegan",
        address="525 Hayes St",
        city="San Francisco",
        state="CA",
        zip_code="94102",
        description="100% plant-based bowls, smoothies, and seasonal specials.",
        phone="(415) 555-0501",
        price_tier=P2,
        amenities=["WiFi", "Takeout", "Delivery", "Outdoor Seating"],
        keywords=["vegan", "healthy", "bowls", "gluten-free"],
        hours=_h(),
    ),
    dict(
        name="Roots & Ritual",
        cuisine_type="Vegan",
        address="428 Castro St",
        city="San Francisco",
        state="CA",
        zip_code="94114",
        description="Fine plant-based tasting menus with wine pairings in a minimalist dining room.",
        phone="(415) 555-0502",
        price_tier=P3,
        amenities=["Reservations", "Tasting menu", "Wine"],
        keywords=["vegan", "fine dining", "romantic", "date night"],
        hours=_h(Tuesday="Closed", Wednesday="Closed"),
    ),
    dict(
        name="Sprout & Stone",
        cuisine_type="Vegan",
        address="1150 Ocean Ave",
        city="San Francisco",
        state="CA",
        zip_code="94112",
        description="Casual vegan pizzas, cashew mac, and dairy-free soft serve.",
        phone="(415) 555-0503",
        price_tier=P1,
        amenities=["Takeout", "Family-friendly"],
        keywords=["vegan", "pizza", "sweet", "casual"],
        hours=_h(),
    ),
    # --- Bakery & dessert & sweet ---
    dict(
        name="Tartine Bakery",
        cuisine_type="French",
        address="600 Guerrero St",
        city="San Francisco",
        state="CA",
        zip_code="94110",
        description="World-renowned artisan bakery. Morning buns and croissants.",
        phone="(415) 555-0601",
        price_tier=P2,
        amenities=["Takeout", "Coffee"],
        keywords=["bakery", "bread", "pastries", "sweet", "brunch"],
        hours=_h(Monday="Closed", Tuesday="Closed"),
    ),
    dict(
        name="Sugar & Steam",
        cuisine_type="Dessert",
        address="2015 Fillmore St",
        city="San Francisco",
        state="CA",
        zip_code="94115",
        description="Hot desserts, soufflés, and craft hot chocolate. Cozy booths for two.",
        phone="(415) 555-0602",
        price_tier=P2,
        amenities=["Dessert only", "Romantic"],
        keywords=["sweet", "dessert", "romantic", "date night"],
        hours=_h(),
    ),
    dict(
        name="Midnight Gelato Lab",
        cuisine_type="Dessert",
        address="1455 Market St",
        city="San Francisco",
        state="CA",
        zip_code="94103",
        description="Small-batch gelato, affogatos, and vegan sorbetto flights.",
        phone="(415) 555-0603",
        price_tier=P1,
        amenities=["Late night", "Takeout"],
        keywords=["sweet", "gelato", "vegan", "late night"],
        hours=_h(Friday="noon-midnight", Saturday="noon-midnight"),
    ),
    dict(
        name="Honeycomb Patisserie",
        cuisine_type="Bakery",
        address="88 Spear St",
        city="San Francisco",
        state="CA",
        zip_code="94105",
        description="French pastries, viennoiserie, and custom celebration cakes.",
        phone="(415) 555-0604",
        price_tier=P2,
        amenities=["Catering", "Coffee"],
        keywords=["bakery", "sweet", "pastries", "special occasion"],
        hours=_h(Saturday="8am-6pm", Sunday="8am-4pm"),
    ),
    # --- French & European ---
    dict(
        name="Bistro Lumière",
        cuisine_type="French",
        address="1550 California St",
        city="San Francisco",
        state="CA",
        zip_code="94109",
        description="Classic French bistro with duck confit, crème brûlée, and candlelight.",
        phone="(415) 555-0701",
        price_tier=P3,
        amenities=["Reservations", "Romantic", "Wine"],
        keywords=["French", "romantic", "fine dining", "sweet"],
        hours=_h(),
    ),
    dict(
        name="Trattoria Verdi",
        cuisine_type="Italian",
        address="3200 Sacramento St",
        city="San Francisco",
        state="CA",
        zip_code="94115",
        description="Neighborhood Italian with house-made tiramisu and limoncello.",
        phone="(415) 555-0702",
        price_tier=P2,
        amenities=["Patio", "Family-friendly"],
        keywords=["Italian", "sweet", "dessert", "casual"],
        hours=_h(),
    ),
    # --- Seafood & BBQ ---
    dict(
        name="Harbor Catch",
        cuisine_type="Seafood",
        address="Pier 39",
        city="San Francisco",
        state="CA",
        zip_code="94133",
        description="Oysters, cioppino, and grilled fish with bay views.",
        phone="(415) 555-0801",
        price_tier=P3,
        amenities=["Waterfront", "Tourist-friendly"],
        keywords=["seafood", "romantic", "view", "special occasion"],
        hours=_h(),
    ),
    dict(
        name="Low & Slow BBQ",
        cuisine_type="BBQ",
        address="4500 3rd St",
        city="San Francisco",
        state="CA",
        zip_code="94124",
        description="Central Texas-style brisket, smoky ribs, and bourbon cocktails.",
        phone="(415) 555-0802",
        price_tier=P2,
        amenities=["Outdoor seating", "Family-friendly"],
        keywords=["BBQ", "comfort food", "casual"],
        hours=_h(),
    ),
    # --- Ethiopian, Spanish, Greek ---
    dict(
        name="Blue Nile Ethiopian",
        cuisine_type="Ethiopian",
        address="3030 Telegraph Ave",
        city="Berkeley",
        state="CA",
        zip_code="94705",
        description="Injera platters, vegan wot stews, and honey wine.",
        phone="(510) 555-0901",
        price_tier=P2,
        amenities=["Vegetarian friendly", "Share plates"],
        keywords=["Ethiopian", "vegan", "spicy", "family"],
        hours=_h(),
    ),
    dict(
        name="Barcelona Tapas",
        cuisine_type="Spanish",
        address="2020 Shattuck Ave",
        city="Berkeley",
        state="CA",
        zip_code="94704",
        description="Patatas bravas, jamón, and churros with chocolate in a lively room.",
        phone="(510) 555-0902",
        price_tier=P2,
        amenities=["Bar", "Small plates"],
        keywords=["tapas", "romantic", "sweet", "wine"],
        hours=_h(),
    ),
    dict(
        name="Athens Table",
        cuisine_type="Greek",
        address="2500 Durant Ave",
        city="Berkeley",
        state="CA",
        zip_code="94704",
        description="Grilled octopus, lamb chops, and honey yogurt with walnuts.",
        phone="(510) 555-0903",
        price_tier=P2,
        amenities=["Patio", "Family-friendly"],
        keywords=["Greek", "Mediterranean", "sweet", "healthy"],
        hours=_h(),
    ),
    # --- Oakland ---
    dict(
        name="Jack London Grill",
        cuisine_type="American",
        address="66 Franklin St",
        city="Oakland",
        state="CA",
        zip_code="94607",
        description="Waterfront steaks and cocktails near the ferry.",
        phone="(510) 555-1001",
        price_tier=P3,
        amenities=["Bar", "View"],
        keywords=["American", "romantic", "fine dining", "date night"],
        hours=_h(),
    ),
    dict(
        name="Temescal Pizza Co",
        cuisine_type="Italian",
        address="4800 Telegraph Ave",
        city="Oakland",
        state="CA",
        zip_code="94609",
        description="Wood-fired Neapolitan pies and burrata starters.",
        phone="(510) 555-1002",
        price_tier=P2,
        amenities=["Family-friendly", "Beer"],
        keywords=["pizza", "casual", "Italian"],
        hours=_h(),
    ),
    dict(
        name="Lake Chalet Sushi",
        cuisine_type="Japanese",
        address="1520 Lakeside Dr",
        city="Oakland",
        state="CA",
        zip_code="94612",
        description="Sushi and rolls with Lake Merritt views at sunset.",
        phone="(510) 555-1003",
        price_tier=P3,
        amenities=["Reservations", "View"],
        keywords=["sushi", "romantic", "date night", "fine dining"],
        hours=_h(),
    ),
    dict(
        name="Oakland Vegan Deli",
        cuisine_type="Vegan",
        address="1433 Peralta St",
        city="Oakland",
        state="CA",
        zip_code="94607",
        description="Sandwiches, salads, and vegan cookies baked daily.",
        phone="(510) 555-1004",
        price_tier=P1,
        amenities=["Takeout", "Lunch"],
        keywords=["vegan", "sweet", "healthy", "casual"],
        hours=_h(Saturday="Closed", Sunday="Closed"),
    ),
    dict(
        name="Smoky Soul BBQ Oakland",
        cuisine_type="BBQ",
        address="301 Broadway",
        city="Oakland",
        state="CA",
        zip_code="94607",
        description="Brisket, links, and banana pudding for dessert.",
        phone="(510) 555-1005",
        price_tier=P2,
        amenities=["Takeout", "Casual"],
        keywords=["BBQ", "sweet", "comfort food"],
        hours=_h(),
    ),
    # --- San Jose ---
    dict(
        name="Santana Row Brasserie",
        cuisine_type="French",
        city="San Jose",
        state="CA",
        zip_code="95128",
        address="377 Santana Row",
        description="Open-air brasserie with steak frites and crêpes suzette.",
        phone="(408) 555-1101",
        price_tier=P3,
        amenities=["Outdoor seating", "Shopping district"],
        keywords=["French", "romantic", "sweet", "fine dining"],
        hours=_h(),
    ),
    dict(
        name="Little Saigon House",
        cuisine_type="Vietnamese",
        address="1180 Story Rd",
        city="San Jose",
        state="CA",
        zip_code="95122",
        description="Pho, bun cha, and che sweet dessert soups.",
        phone="(408) 555-1102",
        price_tier=P1,
        amenities=["Takeout", "Casual"],
        keywords=["Vietnamese", "sweet", "cheap eats"],
        hours=_h(),
    ),
    dict(
        name="Silicon Tandoor",
        cuisine_type="Indian",
        address="98 S Almaden Blvd",
        city="San Jose",
        state="CA",
        zip_code="95113",
        description="Silicon Valley lunch buffet and refined dinner service.",
        phone="(408) 555-1103",
        price_tier=P2,
        amenities=["Buffet", "Delivery"],
        keywords=["Indian", "spicy", "vegan options", "family"],
        hours=_h(),
    ),
    dict(
        name="Rose Garden Izakaya",
        cuisine_type="Japanese",
        address="367 E Taylor St",
        city="San Jose",
        state="CA",
        zip_code="95112",
        description="Izakaya small plates, yakitori, and sake flights.",
        phone="(408) 555-1104",
        price_tier=P2,
        amenities=["Bar", "Late night"],
        keywords=["Japanese", "date night", "casual"],
        hours=_h(),
    ),
    dict(
        name="Willow Glen Creamery",
        cuisine_type="Dessert",
        address="1155 Lincoln Ave",
        city="San Jose",
        state="CA",
        zip_code="95125",
        description="House-made ice cream, vegan coconut bases, and waffle cones.",
        phone="(408) 555-1105",
        price_tier=P1,
        amenities=["Family-friendly", "Takeout"],
        keywords=["sweet", "dessert", "vegan", "kids"],
        hours=_h(),
    ),
    # --- Palo Alto ---
    dict(
        name="University Avenue Bistro",
        cuisine_type="Mediterranean",
        address="520 University Ave",
        city="Palo Alto",
        state="CA",
        zip_code="94301",
        description="Cal-Mediterranean plates and olive oil cakes for dessert.",
        phone="(650) 555-1201",
        price_tier=P3,
        amenities=["Reservations", "Wine"],
        keywords=["Mediterranean", "romantic", "fine dining", "sweet"],
        hours=_h(),
    ),
    dict(
        name="Palo Alto Bakery Lab",
        cuisine_type="Bakery",
        address="200 California Ave",
        city="Palo Alto",
        state="CA",
        zip_code="94306",
        description="Sourdough experiments, croissants, and seasonal fruit tarts.",
        phone="(650) 555-1202",
        price_tier=P2,
        amenities=["Coffee", "WiFi"],
        keywords=["bakery", "sweet", "brunch", "pastries"],
        hours=_h(),
    ),
    dict(
        name="Nob Hill Gardens",
        cuisine_type="American",
        address="100 University Ave",
        city="Palo Alto",
        state="CA",
        zip_code="94301",
        description="Garden patio, tasting menus, sommelier service — special-occasion dining.",
        phone="(650) 555-1203",
        price_tier=P4,
        amenities=["Fine dining", "Garden", "Private events"],
        keywords=["fine dining", "romantic", "special occasion", "upscale"],
        hours=_h(Monday="Closed", Tuesday="Closed"),
    ),
    # --- More SF variety ---
    dict(
        name="Mission Burritos Express",
        cuisine_type="Mexican",
        address="1700 Mission St",
        city="San Francisco",
        state="CA",
        zip_code="94103",
        description="Fast counter-service burritos and agua frescas.",
        phone="(415) 555-1301",
        price_tier=P1,
        amenities=["Takeout"],
        keywords=["Mexican", "cheap eats", "late night"],
        hours=_h(),
    ),
    dict(
        name="Nob Hill Supper Club",
        cuisine_type="American",
        address="1000 California St",
        city="San Francisco",
        state="CA",
        zip_code="94108",
        description="Jazz brunch and prix-fixe dinners in a historic hotel dining room.",
        phone="(415) 555-1302",
        price_tier=P4,
        amenities=["Live music", "Fine dining", "Reservations"],
        keywords=["fine dining", "romantic", "jazz", "special occasion"],
        hours=_h(),
    ),
    dict(
        name="Sunset Ramen House",
        cuisine_type="Japanese",
        address="1730 Irving St",
        city="San Francisco",
        state="CA",
        zip_code="94122",
        description="Rich tonkotsu, vegan miso ramen, and matcha desserts.",
        phone="(415) 555-1303",
        price_tier=P2,
        amenities=["Counter seating", "Takeout"],
        keywords=["ramen", "vegan", "sweet", "casual"],
        hours=_h(),
    ),
    dict(
        name="Castro Creperie",
        cuisine_type="French",
        address="389 Castro St",
        city="San Francisco",
        state="CA",
        zip_code="94114",
        description="Sweet and savory crêpes, Nutella specials, and cider.",
        phone="(415) 555-1304",
        price_tier=P1,
        amenities=["Outdoor seating", "Casual"],
        keywords=["sweet", "dessert", "romantic", "brunch"],
        hours=_h(),
    ),
    dict(
        name="Richmond Thai House",
        cuisine_type="Thai",
        address="602 Clement St",
        city="San Francisco",
        state="CA",
        zip_code="94118",
        description="Regional Thai curries, mango rice, and herbal salads.",
        phone="(415) 555-1305",
        price_tier=P2,
        amenities=["Takeout", "Spicy"],
        keywords=["Thai", "sweet", "spicy", "family"],
        hours=_h(),
    ),
    dict(
        name="SoMa Wine Kitchen",
        cuisine_type="Mediterranean",
        address="555 2nd St",
        city="San Francisco",
        state="CA",
        zip_code="94107",
        description="Wine flights, charcuterie, and chocolate torte pairings.",
        phone="(415) 555-1307",
        price_tier=P3,
        amenities=["Wine bar", "Reservations"],
        keywords=["romantic", "wine", "sweet", "date night"],
        hours=_h(),
    ),
    dict(
        name="Bernal Heights Taqueria",
        cuisine_type="Mexican",
        address="900 Cortland Ave",
        city="San Francisco",
        state="CA",
        zip_code="94110",
        description="Neighborhood taqueria with excellent salsa bar and flan.",
        phone="(415) 555-1308",
        price_tier=P1,
        amenities=["Takeout", "Casual"],
        keywords=["Mexican", "sweet", "dessert", "family"],
        hours=_h(),
    ),
    dict(
        name="Hayes Valley Brasserie",
        cuisine_type="French",
        address="450 Hayes St",
        city="San Francisco",
        state="CA",
        zip_code="94102",
        description="Bistro classics, natural wines, and romantic sidewalk seating.",
        phone="(415) 555-1310",
        price_tier=P3,
        amenities=["Reservations", "Romantic", "Patio"],
        keywords=["French", "romantic", "fine dining", "date night"],
        hours=_h(),
    ),

    # ── 100 additional restaurants (diverse cuisines, cities, price tiers) ──

    # --- Italian (more price tiers & cities) ---
    dict(
        name="Pizzeria Pronto",
        cuisine_type="Italian",
        address="400 Castro St",
        city="Mountain View",
        state="CA",
        zip_code="94041",
        description="Neapolitan pizzas by the slice and whole, with a quick counter-service setup.",
        phone="(650) 555-2001",
        price_tier=P1,
        amenities=["Takeout", "Family-friendly"],
        keywords=["pizza", "cheap eats", "casual", "Italian"],
        hours=_h(),
    ),
    dict(
        name="Bottega Toscana",
        cuisine_type="Italian",
        address="220 University Ave",
        city="Palo Alto",
        state="CA",
        zip_code="94301",
        description="Handcrafted Florentine dishes, truffle risotto, and an extensive Italian wine cellar.",
        phone="(650) 555-2002",
        price_tier=P4,
        amenities=["Fine dining", "Wine cellar", "Reservations", "Private dining"],
        keywords=["fine dining", "romantic", "Italian", "special occasion", "truffle"],
        hours=_h(Monday="Closed"),
    ),
    dict(
        name="La Cucina Felice",
        cuisine_type="Italian",
        address="1900 Park Blvd",
        city="Oakland",
        state="CA",
        zip_code="94606",
        description="Family-run trattioria with wood-fired pastas and house-made cannoli.",
        phone="(510) 555-2003",
        price_tier=P2,
        amenities=["Family-friendly", "Outdoor Seating"],
        keywords=["Italian", "pasta", "dessert", "sweet", "casual"],
        hours=_h(),
    ),
    dict(
        name="Ristorante Amalfi",
        cuisine_type="Italian",
        address="88 Santana Row",
        city="San Jose",
        state="CA",
        zip_code="95128",
        description="Southern Italian coastal cuisine: fresh seafood linguine and limoncello sorbet.",
        phone="(408) 555-2004",
        price_tier=P3,
        amenities=["Reservations", "Full bar", "Romantic"],
        keywords=["Italian", "seafood", "romantic", "date night"],
        hours=_h(),
    ),
    dict(
        name="Sfoglia Pasta Bar",
        cuisine_type="Italian",
        address="1550 Solano Ave",
        city="Berkeley",
        state="CA",
        zip_code="94707",
        description="Fresh-rolled pasta made daily, all-natural sauces, and gelato to finish.",
        phone="(510) 555-2005",
        price_tier=P2,
        amenities=["Takeout", "Vegetarian options"],
        keywords=["pasta", "Italian", "casual", "healthy", "dessert"],
        hours=_h(),
    ),

    # --- Mexican (P3, P4, more cities) ---
    dict(
        name="Hacienda Real",
        cuisine_type="Mexican",
        address="500 El Camino Real",
        city="Sunnyvale",
        state="CA",
        zip_code="94087",
        description="Upscale Mexican with mole negro, mezcal cocktails, and tableside guacamole.",
        phone="(408) 555-2101",
        price_tier=P3,
        amenities=["Full bar", "Reservations", "Outdoor Seating"],
        keywords=["Mexican", "upscale", "romantic", "date night", "cocktails"],
        hours=_h(),
    ),
    dict(
        name="Casa de Alta California",
        cuisine_type="Mexican",
        address="101 3rd St",
        city="San Francisco",
        state="CA",
        zip_code="94103",
        description="Chef-driven Cal-Mexican with dry-aged beef tacos, lobster enchiladas, and rare agave spirits.",
        phone="(415) 555-2102",
        price_tier=P4,
        amenities=["Fine dining", "Tasting menu", "Bar", "Reservations"],
        keywords=["Mexican", "fine dining", "special occasion", "tasting menu", "cocktails"],
        hours=_h(Monday="Closed", Tuesday="Closed"),
    ),
    dict(
        name="Taco Libre",
        cuisine_type="Mexican",
        address="700 International Blvd",
        city="Oakland",
        state="CA",
        zip_code="94606",
        description="No-frills taco truck turned brick-and-mortar. Best carne asada in the East Bay.",
        phone="(510) 555-2103",
        price_tier=P1,
        amenities=["Takeout", "Casual"],
        keywords=["tacos", "Mexican", "cheap eats", "late night"],
        hours=_h(Friday="10am-2am", Saturday="10am-2am"),
    ),
    dict(
        name="Cantina Moderna",
        cuisine_type="Mexican",
        address="200 Castro St",
        city="Mountain View",
        state="CA",
        zip_code="94041",
        description="Modern Mexican with farm-fresh ingredients, craft margaritas, and rooftop seating.",
        phone="(650) 555-2104",
        price_tier=P2,
        amenities=["Outdoor Seating", "Bar", "Family-friendly"],
        keywords=["Mexican", "margaritas", "casual", "family"],
        hours=_h(),
    ),

    # --- Chinese (P1–P4, multiple cities) ---
    dict(
        name="Dim Sum Palace",
        cuisine_type="Chinese",
        address="1850 El Camino Real",
        city="Millbrae",
        state="CA",
        zip_code="94030",
        description="Hong Kong-style dim sum served cart-style from 7am. Always packed on weekends.",
        phone="(650) 555-2201",
        price_tier=P2,
        amenities=["Family-friendly", "Parking", "Group-friendly"],
        keywords=["dim sum", "Chinese", "family", "brunch"],
        hours=_h(Saturday="7am-3pm", Sunday="7am-3pm"),
    ),
    dict(
        name="Hunan Garden",
        cuisine_type="Chinese",
        address="2600 Telegraph Ave",
        city="Oakland",
        state="CA",
        zip_code="94609",
        description="Fiery Hunan province specialties: chili-braised pork and cumin lamb.",
        phone="(510) 555-2202",
        price_tier=P1,
        amenities=["Takeout", "Casual", "BYOB"],
        keywords=["Chinese", "spicy", "cheap eats"],
        hours=_h(),
    ),
    dict(
        name="Peking Duck House",
        cuisine_type="Chinese",
        address="635 Jackson St",
        city="San Francisco",
        state="CA",
        zip_code="94133",
        description="Signature Beijing roasted duck carved tableside, served with handmade pancakes.",
        phone="(415) 555-2203",
        price_tier=P3,
        amenities=["Reservations", "Group-friendly"],
        keywords=["Chinese", "duck", "romantic", "special occasion"],
        hours=_h(),
    ),
    dict(
        name="Imperial Court",
        cuisine_type="Chinese",
        address="300 S Market St",
        city="San Jose",
        state="CA",
        zip_code="95113",
        description="Cantonese fine dining: abalone, XO razor clams, and a 500-label wine list.",
        phone="(408) 555-2204",
        price_tier=P4,
        amenities=["Fine dining", "Private dining", "Wine cellar", "Reservations"],
        keywords=["Chinese", "fine dining", "special occasion", "upscale"],
        hours=_h(Monday="Closed"),
    ),
    dict(
        name="Shanghai Dumplings",
        cuisine_type="Chinese",
        address="1940 S De Anza Blvd",
        city="Cupertino",
        state="CA",
        zip_code="95014",
        description="Soup dumplings, scallion pancakes, and hand-pulled noodles made fresh daily.",
        phone="(408) 555-2205",
        price_tier=P1,
        amenities=["Takeout", "Family-friendly"],
        keywords=["Chinese", "dumplings", "cheap eats", "noodles"],
        hours=_h(),
    ),
    dict(
        name="Golden Phoenix",
        cuisine_type="Chinese",
        address="400 Clement St",
        city="San Francisco",
        state="CA",
        zip_code="94118",
        description="Intimate Cantonese kitchen with delicate steamed fish and lotus leaf rice.",
        phone="(415) 555-2206",
        price_tier=P2,
        amenities=["Takeout", "Casual"],
        keywords=["Chinese", "seafood", "family"],
        hours=_h(),
    ),

    # --- Japanese (P1, P4 + more cities) ---
    dict(
        name="Ramen Yokocho",
        cuisine_type="Japanese",
        address="1200 Saratoga Ave",
        city="San Jose",
        state="CA",
        zip_code="95129",
        description="Counter-style ramen bar with rich pork bone broth and truffle mazemen.",
        phone="(408) 555-2301",
        price_tier=P1,
        amenities=["Counter seating", "Takeout"],
        keywords=["ramen", "Japanese", "cheap eats", "casual"],
        hours=_h(),
    ),
    dict(
        name="Kaiseki Nishimura",
        cuisine_type="Japanese",
        address="340 Post St",
        city="San Francisco",
        state="CA",
        zip_code="94108",
        description="Traditional multi-course kaiseki with seasonal ingredients and sake pairings.",
        phone="(415) 555-2302",
        price_tier=P4,
        amenities=["Fine dining", "Tasting menu", "Reservations", "Sake bar"],
        keywords=["Japanese", "fine dining", "tasting menu", "date night", "special occasion"],
        hours=_h(Monday="Closed", Sunday="Closed"),
    ),
    dict(
        name="Udon Collective",
        cuisine_type="Japanese",
        address="1600 Park St",
        city="Alameda",
        state="CA",
        zip_code="94501",
        description="House-pulled thick udon in dashi broth, tempura sides, and matcha soft serve.",
        phone="(510) 555-2303",
        price_tier=P2,
        amenities=["Takeout", "Family-friendly"],
        keywords=["Japanese", "udon", "sweet", "casual"],
        hours=_h(),
    ),
    dict(
        name="Omakase by Hiroshi",
        cuisine_type="Japanese",
        address="2050 University Ave",
        city="Berkeley",
        state="CA",
        zip_code="94704",
        description="Intimate 12-seat omakase counter with Edomae-style sushi by Chef Hiroshi.",
        phone="(510) 555-2304",
        price_tier=P4,
        amenities=["Tasting menu", "Reservations", "BYOB"],
        keywords=["sushi", "omakase", "fine dining", "date night", "special occasion"],
        hours=_h(Monday="Closed", Tuesday="Closed", Wednesday="Closed"),
    ),
    dict(
        name="Miso Hungry",
        cuisine_type="Japanese",
        address="890 Blossom Hill Rd",
        city="San Jose",
        state="CA",
        zip_code="95123",
        description="Fun izakaya plates, ramen, and Japanese whisky highballs in a casual setting.",
        phone="(408) 555-2305",
        price_tier=P2,
        amenities=["Bar", "Late night", "Group-friendly"],
        keywords=["Japanese", "izakaya", "casual", "late night", "cocktails"],
        hours=_h(Friday="11am-midnight", Saturday="11am-midnight"),
    ),

    # --- Indian (P1, P3, P4 + more cities) ---
    dict(
        name="Curry in a Hurry",
        cuisine_type="Indian",
        address="1110 Saratoga Ave",
        city="Santa Clara",
        state="CA",
        zip_code="95050",
        description="Fast-casual Indian lunch bowls, tikka wraps, and mango lassi.",
        phone="(408) 555-2401",
        price_tier=P1,
        amenities=["Takeout", "Delivery", "Casual"],
        keywords=["Indian", "cheap eats", "healthy", "lunch"],
        hours=_h(Saturday="Closed", Sunday="Closed"),
    ),
    dict(
        name="Zaika Fine Indian",
        cuisine_type="Indian",
        address="388 Market St",
        city="San Francisco",
        state="CA",
        zip_code="94111",
        description="Modern Indian tasting menus with sous vide lamb, foie gras kulfi, and premium whisky pairings.",
        phone="(415) 555-2402",
        price_tier=P4,
        amenities=["Fine dining", "Tasting menu", "Reservations", "Bar"],
        keywords=["Indian", "fine dining", "tasting menu", "special occasion", "upscale"],
        hours=_h(Monday="Closed"),
    ),
    dict(
        name="Punjab Dhaba",
        cuisine_type="Indian",
        address="360 Grand Ave",
        city="Oakland",
        state="CA",
        zip_code="94610",
        description="Hearty Punjabi home cooking: sarson da saag, makki di roti, and lassi.",
        phone="(510) 555-2403",
        price_tier=P1,
        amenities=["Takeout", "Family-friendly"],
        keywords=["Indian", "vegan", "cheap eats", "comfort food"],
        hours=_h(),
    ),
    dict(
        name="Bombay Club",
        cuisine_type="Indian",
        address="1730 El Camino Real",
        city="Palo Alto",
        state="CA",
        zip_code="94306",
        description="Upscale Indian with a curated gin and tonic bar, tasting platters, and live tabla music.",
        phone="(650) 555-2404",
        price_tier=P3,
        amenities=["Bar", "Live music", "Reservations"],
        keywords=["Indian", "upscale", "romantic", "cocktails", "date night"],
        hours=_h(),
    ),
    dict(
        name="Desi Kitchen",
        cuisine_type="Indian",
        address="4200 Fremont Blvd",
        city="Fremont",
        state="CA",
        zip_code="94536",
        description="Biryani specialists and street chaat in a colorful, casual space.",
        phone="(510) 555-2405",
        price_tier=P2,
        amenities=["Takeout", "Casual", "Family-friendly"],
        keywords=["Indian", "biryani", "spicy", "family"],
        hours=_h(),
    ),

    # --- American (more P1, diverse cities) ---
    dict(
        name="Fender's Burger Bar",
        cuisine_type="American",
        address="2200 Shattuck Ave",
        city="Berkeley",
        state="CA",
        zip_code="94704",
        description="Smash burgers, curly fries, and craft root beer floats.",
        phone="(510) 555-2501",
        price_tier=P1,
        amenities=["Takeout", "Counter service"],
        keywords=["burgers", "American", "cheap eats", "sweet", "casual"],
        hours=_h(),
    ),
    dict(
        name="The Presidio Table",
        cuisine_type="American",
        address="1 Lincoln Blvd",
        city="San Francisco",
        state="CA",
        zip_code="94129",
        description="Seasonal California cuisine in a landmark Presidio building with park views.",
        phone="(415) 555-2502",
        price_tier=P4,
        amenities=["Fine dining", "Reservations", "View", "Private events"],
        keywords=["American", "fine dining", "romantic", "special occasion", "view"],
        hours=_h(),
    ),
    dict(
        name="Sunrise Diner",
        cuisine_type="American",
        address="780 S 1st St",
        city="San Jose",
        state="CA",
        zip_code="95110",
        description="All-day breakfast diner with pancake stacks, biscuit gravy, and bottomless coffee.",
        phone="(408) 555-2503",
        price_tier=P1,
        amenities=["Family-friendly", "WiFi", "Takeout"],
        keywords=["American", "brunch", "breakfast", "cheap eats", "sweet"],
        hours=_h(Saturday="7am-4pm", Sunday="7am-4pm"),
    ),
    dict(
        name="Wildflower Kitchen",
        cuisine_type="American",
        address="700 University Ave",
        city="Palo Alto",
        state="CA",
        zip_code="94301",
        description="Farm-to-fork with rotating seasonal menus and a greenhouse dining room.",
        phone="(650) 555-2504",
        price_tier=P3,
        amenities=["Reservations", "Outdoor Seating", "Wine"],
        keywords=["American", "farm-to-table", "healthy", "romantic"],
        hours=_h(),
    ),
    dict(
        name="Bayside Smokehouse",
        cuisine_type="American",
        address="200 Jack London Square",
        city="Oakland",
        state="CA",
        zip_code="94607",
        description="Waterfront smokehouse with competition-level ribs and craft beer list.",
        phone="(510) 555-2505",
        price_tier=P2,
        amenities=["Outdoor Seating", "Bar", "Waterfront"],
        keywords=["BBQ", "American", "view", "casual", "beer"],
        hours=_h(),
    ),
    dict(
        name="Route 66 Diner",
        cuisine_type="American",
        address="400 Fremont Blvd",
        city="Fremont",
        state="CA",
        zip_code="94536",
        description="Classic roadside diner with mile-high club sandwiches and pie slices.",
        phone="(510) 555-2506",
        price_tier=P1,
        amenities=["Takeout", "Family-friendly", "WiFi"],
        keywords=["American", "burgers", "sweet", "cheap eats", "pie"],
        hours=_h(),
    ),

    # --- Thai (P1, P3, P4 + more cities) ---
    dict(
        name="Thai Street Food Stall",
        cuisine_type="Thai",
        address="1100 Story Rd",
        city="San Jose",
        state="CA",
        zip_code="95122",
        description="Authentic Bangkok street food: pad see ew, papaya salad, and mango sticky rice.",
        phone="(408) 555-2601",
        price_tier=P1,
        amenities=["Takeout", "Casual"],
        keywords=["Thai", "cheap eats", "sweet", "spicy"],
        hours=_h(),
    ),
    dict(
        name="The Elephant Room",
        cuisine_type="Thai",
        address="666 Sutter St",
        city="San Francisco",
        state="CA",
        zip_code="94102",
        description="Contemporary Thai with modern plating, natural wine list, and a rooftop bar.",
        phone="(415) 555-2602",
        price_tier=P3,
        amenities=["Bar", "Reservations", "Rooftop"],
        keywords=["Thai", "upscale", "cocktails", "date night", "romantic"],
        hours=_h(),
    ),
    dict(
        name="Lotus Thai Fine Dining",
        cuisine_type="Thai",
        address="1 Market Plaza",
        city="San Francisco",
        state="CA",
        zip_code="94105",
        description="Award-winning Thai tasting menu with royal palace recipes and rare Thai whisky.",
        phone="(415) 555-2603",
        price_tier=P4,
        amenities=["Fine dining", "Tasting menu", "Reservations", "Private dining"],
        keywords=["Thai", "fine dining", "special occasion", "tasting menu"],
        hours=_h(Monday="Closed", Sunday="Closed"),
    ),
    dict(
        name="Siam Kitchen",
        cuisine_type="Thai",
        address="3500 Telegraph Ave",
        city="Oakland",
        state="CA",
        zip_code="94609",
        description="Neighborhood Thai with generous portions, spicy basil stir-fries, and iced tea.",
        phone="(510) 555-2604",
        price_tier=P2,
        amenities=["Takeout", "Family-friendly"],
        keywords=["Thai", "spicy", "family", "casual"],
        hours=_h(),
    ),
    dict(
        name="Chiang Mai House",
        cuisine_type="Thai",
        address="2100 El Camino Real",
        city="Santa Clara",
        state="CA",
        zip_code="95050",
        description="Northern Thai cuisine from Chiang Mai: khao soi, sai oua sausage, and coconut pudding.",
        phone="(408) 555-2605",
        price_tier=P2,
        amenities=["Vegetarian options", "Takeout"],
        keywords=["Thai", "spicy", "sweet", "healthy"],
        hours=_h(),
    ),

    # --- Mediterranean (P1, P2, P4 + more cities) ---
    dict(
        name="Falafel Kingdom",
        cuisine_type="Mediterranean",
        address="1400 Shattuck Ave",
        city="Berkeley",
        state="CA",
        zip_code="94709",
        description="Crispy falafel, creamy hummus, and stuffed grape leaves in a casual counter setting.",
        phone="(510) 555-2701",
        price_tier=P1,
        amenities=["Takeout", "Vegan", "Casual"],
        keywords=["Mediterranean", "vegan", "healthy", "cheap eats"],
        hours=_h(),
    ),
    dict(
        name="Taverna Aegean",
        cuisine_type="Mediterranean",
        address="1200 Blossom Hill Rd",
        city="San Jose",
        state="CA",
        zip_code="95118",
        description="Lively taverna with mezze spreads, roasted lamb, and live bouzouki nights.",
        phone="(408) 555-2702",
        price_tier=P2,
        amenities=["Live music", "Group-friendly", "Patio"],
        keywords=["Mediterranean", "Greek", "romantic", "family"],
        hours=_h(),
    ),
    dict(
        name="Levant Kitchen",
        cuisine_type="Mediterranean",
        address="3200 College Ave",
        city="Oakland",
        state="CA",
        zip_code="94618",
        description="Lebanese and Levantine food: kibbeh, shawarma wraps, and knafeh for dessert.",
        phone="(510) 555-2703",
        price_tier=P2,
        amenities=["Takeout", "Vegetarian options"],
        keywords=["Mediterranean", "sweet", "dessert", "healthy"],
        hours=_h(),
    ),
    dict(
        name="Riviera Table",
        cuisine_type="Mediterranean",
        address="500 Mathilda Ave",
        city="Sunnyvale",
        state="CA",
        zip_code="94086",
        description="Provençal-meets-Maghreb tasting menus, natural wine, and oud music evenings.",
        phone="(408) 555-2704",
        price_tier=P4,
        amenities=["Fine dining", "Tasting menu", "Reservations", "Live music"],
        keywords=["Mediterranean", "fine dining", "romantic", "date night", "special occasion"],
        hours=_h(Monday="Closed", Tuesday="Closed"),
    ),
    dict(
        name="Pita Stop",
        cuisine_type="Mediterranean",
        address="900 Lincoln Ave",
        city="San Jose",
        state="CA",
        zip_code="95125",
        description="Quick pita wraps, baba ganoush, and tabbouleh. Ideal for lunch.",
        phone="(408) 555-2705",
        price_tier=P1,
        amenities=["Takeout", "Delivery"],
        keywords=["Mediterranean", "healthy", "cheap eats", "lunch"],
        hours=_h(Saturday="Closed", Sunday="Closed"),
    ),

    # --- French (P1, P4 + more cities) ---
    dict(
        name="Petit Pain",
        cuisine_type="French",
        address="200 Main St",
        city="Los Altos",
        state="CA",
        zip_code="94022",
        description="Neighborhood French bakery with baguettes, pain au chocolat, and café crème.",
        phone="(650) 555-2801",
        price_tier=P1,
        amenities=["Coffee", "Takeout"],
        keywords=["French", "bakery", "sweet", "brunch", "pastries"],
        hours=_h(Saturday="7am-4pm", Sunday="7am-2pm"),
    ),
    dict(
        name="Le Grand Véfour SF",
        cuisine_type="French",
        address="580 California St",
        city="San Francisco",
        state="CA",
        zip_code="94104",
        description="Parisian grand dining reimagined in San Francisco: foie gras, tournedos Rossini, and a champagne trolley.",
        phone="(415) 555-2802",
        price_tier=P4,
        amenities=["Fine dining", "Champagne bar", "Reservations", "Private dining"],
        keywords=["French", "fine dining", "romantic", "special occasion", "champagne"],
        hours=_h(Monday="Closed", Saturday="6pm-11pm", Sunday="Closed"),
    ),
    dict(
        name="Bistro du Soleil",
        cuisine_type="French",
        address="800 Bancroft Way",
        city="Berkeley",
        state="CA",
        zip_code="94710",
        description="Sunny Provençal bistro: socca, ratatouille, and tarte Tatin.",
        phone="(510) 555-2803",
        price_tier=P2,
        amenities=["Patio", "Reservations"],
        keywords=["French", "casual", "sweet", "romantic"],
        hours=_h(),
    ),
    dict(
        name="Café Parisien",
        cuisine_type="French",
        address="1000 El Camino Real",
        city="Menlo Park",
        state="CA",
        zip_code="94025",
        description="All-day French café with croque monsieur, quiche, and afternoon wine service.",
        phone="(650) 555-2804",
        price_tier=P2,
        amenities=["WiFi", "Coffee", "Outdoor Seating"],
        keywords=["French", "brunch", "coffee", "casual", "sweet"],
        hours=_h(),
    ),

    # --- Korean (P1, P2, P3, P4 + more cities) ---
    dict(
        name="K-Street Snacks",
        cuisine_type="Korean",
        address="220 5th St",
        city="San Francisco",
        state="CA",
        zip_code="94103",
        description="Korean street food counter: tteokbokki, corn dogs, and bingsu shaved ice.",
        phone="(415) 555-2901",
        price_tier=P1,
        amenities=["Takeout", "Counter service"],
        keywords=["Korean", "sweet", "cheap eats", "dessert", "casual"],
        hours=_h(Friday="11am-midnight", Saturday="11am-midnight"),
    ),
    dict(
        name="Gogi Garden",
        cuisine_type="Korean",
        address="1700 El Camino Real",
        city="Burlingame",
        state="CA",
        zip_code="94010",
        description="Korean BBQ with premium wagyu, banchan bar, and soju cocktails.",
        phone="(650) 555-2902",
        price_tier=P3,
        amenities=["BBQ tables", "Bar", "Reservations", "Group-friendly"],
        keywords=["Korean BBQ", "romantic", "upscale", "wagyu"],
        hours=_h(),
    ),
    dict(
        name="Seoul Spa Café",
        cuisine_type="Korean",
        address="1200 S De Anza Blvd",
        city="San Jose",
        state="CA",
        zip_code="95129",
        description="Korean brunch café with gyeran-bap, shrimp toast, and matcha dalgona coffee.",
        phone="(408) 555-2903",
        price_tier=P2,
        amenities=["Coffee", "Brunch", "WiFi"],
        keywords=["Korean", "brunch", "sweet", "coffee", "casual"],
        hours=_h(Monday="Closed"),
    ),
    dict(
        name="Hanok Fine Korean",
        cuisine_type="Korean",
        address="452 Geary St",
        city="San Francisco",
        state="CA",
        zip_code="94102",
        description="Modern hansik tasting menus featuring ganjang-marinated crab and makgeolli pairings.",
        phone="(415) 555-2904",
        price_tier=P4,
        amenities=["Fine dining", "Tasting menu", "Reservations"],
        keywords=["Korean", "fine dining", "tasting menu", "date night", "special occasion"],
        hours=_h(Monday="Closed", Sunday="Closed"),
    ),
    dict(
        name="Kimchi Republic",
        cuisine_type="Korean",
        address="3000 Telegraph Ave",
        city="Oakland",
        state="CA",
        zip_code="94609",
        description="Classic Korean comfort food: sundubu jjigae, doenjang soup, and soondubu.",
        phone="(510) 555-2905",
        price_tier=P2,
        amenities=["Takeout", "Casual"],
        keywords=["Korean", "comfort food", "family", "spicy"],
        hours=_h(),
    ),

    # --- Vietnamese (P2, P3, P4 + more cities) ---
    dict(
        name="Pho Saigon Gold",
        cuisine_type="Vietnamese",
        address="3200 Story Rd",
        city="San Jose",
        state="CA",
        zip_code="95127",
        description="Premium pho broth simmered 24 hours with wagyu brisket and heirloom herbs.",
        phone="(408) 555-3001",
        price_tier=P2,
        amenities=["Family-friendly", "Takeout"],
        keywords=["Vietnamese", "pho", "healthy", "casual"],
        hours=_h(),
    ),
    dict(
        name="Nam Hai",
        cuisine_type="Vietnamese",
        address="660 Sacramento St",
        city="San Francisco",
        state="CA",
        zip_code="94111",
        description="Modern Central Vietnamese: charcoal-grilled pork skewers, mi quang noodles, and che desserts.",
        phone="(415) 555-3002",
        price_tier=P3,
        amenities=["Reservations", "Full bar"],
        keywords=["Vietnamese", "sweet", "romantic", "date night"],
        hours=_h(),
    ),
    dict(
        name="Hanoi Silk",
        cuisine_type="Vietnamese",
        address="160 Geary St",
        city="San Francisco",
        state="CA",
        zip_code="94108",
        description="Fine dining Vietnamese with cha ca la vong, lobster pho, and French-Vietnamese wine pairings.",
        phone="(415) 555-3003",
        price_tier=P4,
        amenities=["Fine dining", "Tasting menu", "Reservations", "Wine"],
        keywords=["Vietnamese", "fine dining", "special occasion", "romantic"],
        hours=_h(Monday="Closed"),
    ),
    dict(
        name="Bun Bo Hue Express",
        cuisine_type="Vietnamese",
        address="780 S 1st St",
        city="San Jose",
        state="CA",
        zip_code="95110",
        description="Spicy Hue-style beef noodle soup, banh mi, and fresh spring rolls.",
        phone="(408) 555-3004",
        price_tier=P1,
        amenities=["Takeout", "Casual"],
        keywords=["Vietnamese", "spicy", "cheap eats", "noodles"],
        hours=_h(),
    ),
    dict(
        name="Mekong Garden",
        cuisine_type="Vietnamese",
        address="1400 Park St",
        city="Alameda",
        state="CA",
        zip_code="94501",
        description="Garden-view Vietnamese with lemongrass prawns and ginger crème caramel.",
        phone="(510) 555-3005",
        price_tier=P2,
        amenities=["Outdoor Seating", "Family-friendly"],
        keywords=["Vietnamese", "sweet", "romantic", "view"],
        hours=_h(),
    ),

    # --- Greek (P1, P3, P4) ---
    dict(
        name="Gyro Corner",
        cuisine_type="Greek",
        address="1600 Mission St",
        city="San Francisco",
        state="CA",
        zip_code="94103",
        description="Fast gyros, souvlaki wraps, and loukoumades (honey donuts) for dessert.",
        phone="(415) 555-3101",
        price_tier=P1,
        amenities=["Takeout", "Counter service"],
        keywords=["Greek", "cheap eats", "sweet", "dessert"],
        hours=_h(),
    ),
    dict(
        name="Mykonos on the Bay",
        cuisine_type="Greek",
        address="20 Embarcadero",
        city="San Francisco",
        state="CA",
        zip_code="94105",
        description="Upscale Greek with freshly caught whole fish, grilled by weight, and baklava ice cream.",
        phone="(415) 555-3102",
        price_tier=P3,
        amenities=["Waterfront", "Reservations", "Full bar"],
        keywords=["Greek", "seafood", "romantic", "view", "fine dining"],
        hours=_h(),
    ),
    dict(
        name="Poseidon Fine Greek",
        cuisine_type="Greek",
        address="100 El Camino Real",
        city="Atherton",
        state="CA",
        zip_code="94027",
        description="Michelin-level Greek cuisine: wagyu saganaki, langoustine avgolemon, and mastiha cocktails.",
        phone="(650) 555-3103",
        price_tier=P4,
        amenities=["Fine dining", "Tasting menu", "Reservations", "Valet"],
        keywords=["Greek", "fine dining", "romantic", "special occasion", "upscale"],
        hours=_h(Monday="Closed", Tuesday="Closed"),
    ),
    dict(
        name="Acropolis Grill",
        cuisine_type="Greek",
        address="4100 MacArthur Blvd",
        city="Oakland",
        state="CA",
        zip_code="94619",
        description="Casual Greek with mousaka, spanakopita, and weekend lamb roasts.",
        phone="(510) 555-3104",
        price_tier=P2,
        amenities=["Family-friendly", "Group-friendly", "Patio"],
        keywords=["Greek", "family", "casual", "Mediterranean"],
        hours=_h(),
    ),
    dict(
        name="Santorini Sunset",
        cuisine_type="Greek",
        address="600 Santana Row",
        city="San Jose",
        state="CA",
        zip_code="95128",
        description="Rooftop Greek bar and grill with tzatziki towers, grilled octopus, and Aegean cocktails.",
        phone="(408) 555-3105",
        price_tier=P3,
        amenities=["Rooftop", "Bar", "Reservations", "Outdoor Seating"],
        keywords=["Greek", "romantic", "cocktails", "view", "date night"],
        hours=_h(),
    ),

    # --- More SF neighborhoods to fill in gaps ---
    dict(
        name="Chinatown Congee House",
        cuisine_type="Chinese",
        address="820 Sacramento St",
        city="San Francisco",
        state="CA",
        zip_code="94108",
        description="Congee, century egg, and crispy fried taro. Comfort food for all occasions.",
        phone="(415) 555-3201",
        price_tier=P1,
        amenities=["Takeout", "Family-friendly"],
        keywords=["Chinese", "cheap eats", "comfort food", "breakfast"],
        hours=_h(Saturday="7am-9pm", Sunday="7am-9pm"),
    ),
    dict(
        name="Sichuan Flame",
        cuisine_type="Chinese",
        address="700 Irving St",
        city="San Francisco",
        state="CA",
        zip_code="94122",
        description="Numbing Sichuan hot pots, mapo tofu, and chilled dan dan noodles.",
        phone="(415) 555-3202",
        price_tier=P2,
        amenities=["Group-friendly", "Takeout", "Spicy"],
        keywords=["Chinese", "spicy", "hot pot", "casual"],
        hours=_h(),
    ),
    dict(
        name="Japantown Curry",
        cuisine_type="Japanese",
        address="1737 Post St",
        city="San Francisco",
        state="CA",
        zip_code="94115",
        description="Japanese curry rice, katsu sandwiches, and mochi ice cream in the heart of Japantown.",
        phone="(415) 555-3203",
        price_tier=P1,
        amenities=["Takeout", "Counter service"],
        keywords=["Japanese", "cheap eats", "sweet", "casual"],
        hours=_h(),
    ),
    dict(
        name="Haight Ashbury Thai",
        cuisine_type="Thai",
        address="1600 Haight St",
        city="San Francisco",
        state="CA",
        zip_code="94117",
        description="Vibrant neighborhood Thai with extensive vegan menu and turmeric cocktails.",
        phone="(415) 555-3204",
        price_tier=P2,
        amenities=["Vegan", "Bar", "Outdoor Seating"],
        keywords=["Thai", "vegan", "spicy", "casual"],
        hours=_h(),
    ),
    dict(
        name="Excelsior Taqueria",
        cuisine_type="Mexican",
        address="4400 Mission St",
        city="San Francisco",
        state="CA",
        zip_code="94112",
        description="Hole-in-the-wall tacos with house-made salsa verde and agua fresca.",
        phone="(415) 555-3205",
        price_tier=P1,
        amenities=["Takeout", "Casual"],
        keywords=["Mexican", "cheap eats", "tacos", "late night"],
        hours=_h(Friday="10am-2am", Saturday="10am-2am"),
    ),
    dict(
        name="Potrero Hill Osteria",
        cuisine_type="Italian",
        address="1300 18th St",
        city="San Francisco",
        state="CA",
        zip_code="94107",
        description="Cozy osteria with seasonal risotto, house amaro, and natural wine.",
        phone="(415) 555-3206",
        price_tier=P3,
        amenities=["Reservations", "Wine bar", "Romantic"],
        keywords=["Italian", "romantic", "date night", "wine"],
        hours=_h(),
    ),
    dict(
        name="Dogpatch Ramen Co",
        cuisine_type="Japanese",
        address="900 22nd St",
        city="San Francisco",
        state="CA",
        zip_code="94107",
        description="Small-batch tonkotsu and shoyu ramen in a converted warehouse.",
        phone="(415) 555-3207",
        price_tier=P2,
        amenities=["Counter seating", "Beer"],
        keywords=["ramen", "Japanese", "casual", "beer"],
        hours=_h(Monday="Closed"),
    ),
    dict(
        name="Outer Sunset Vietnamese",
        cuisine_type="Vietnamese",
        address="2300 Irving St",
        city="San Francisco",
        state="CA",
        zip_code="94122",
        description="Family-run bánh xèo, broken rice plates, and Vietnamese iced coffee.",
        phone="(415) 555-3208",
        price_tier=P2,
        amenities=["Family-friendly", "Takeout"],
        keywords=["Vietnamese", "casual", "family", "cheap eats"],
        hours=_h(),
    ),
    dict(
        name="The Marina Indian Bistro",
        cuisine_type="Indian",
        address="2270 Chestnut St",
        city="San Francisco",
        state="CA",
        zip_code="94123",
        description="Modern Indian bistro with craft cocktails and butter chicken flatbreads.",
        phone="(415) 555-3209",
        price_tier=P2,
        amenities=["Bar", "Outdoor Seating"],
        keywords=["Indian", "casual", "cocktails"],
        hours=_h(),
    ),
    dict(
        name="North Beach Korean BBQ",
        cuisine_type="Korean",
        address="500 Columbus Ave",
        city="San Francisco",
        state="CA",
        zip_code="94133",
        description="Table-top BBQ with late-night drinking menus and Korean fried chicken.",
        phone="(415) 555-3210",
        price_tier=P2,
        amenities=["BBQ tables", "Late night", "Bar"],
        keywords=["Korean BBQ", "late night", "casual", "fun"],
        hours=_h(Friday="11am-1am", Saturday="11am-1am"),
    ),
    dict(
        name="Financial District French Café",
        cuisine_type="French",
        address="333 Bush St",
        city="San Francisco",
        state="CA",
        zip_code="94104",
        description="Quick lunch crêpes, tartines, and café au lait for the downtown crowd.",
        phone="(415) 555-3211",
        price_tier=P2,
        amenities=["WiFi", "Takeout", "Coffee"],
        keywords=["French", "lunch", "coffee", "brunch"],
        hours=_h(Saturday="Closed", Sunday="Closed"),
    ),
    dict(
        name="Greek on Geary",
        cuisine_type="Greek",
        address="2200 Geary Blvd",
        city="San Francisco",
        state="CA",
        zip_code="94115",
        description="BYOB family Greek with lamb kleftiko and homemade baklava.",
        phone="(415) 555-3212",
        price_tier=P2,
        amenities=["BYOB", "Family-friendly"],
        keywords=["Greek", "sweet", "dessert", "family"],
        hours=_h(),
    ),
    dict(
        name="The American Grille",
        cuisine_type="American",
        address="400 4th St",
        city="San Francisco",
        state="CA",
        zip_code="94107",
        description="SoMa power-lunch burgers, craft beers, and truffle fries.",
        phone="(415) 555-3213",
        price_tier=P2,
        amenities=["Bar", "WiFi"],
        keywords=["American", "burgers", "casual", "beer"],
        hours=_h(),
    ),
    dict(
        name="Mediterra Oakland",
        cuisine_type="Mediterranean",
        address="4900 Piedmont Ave",
        city="Oakland",
        state="CA",
        zip_code="94611",
        description="Neighborhood staple for hummus, za'atar flatbreads, and crispy falafel.",
        phone="(510) 555-3214",
        price_tier=P2,
        amenities=["Vegan", "Outdoor Seating"],
        keywords=["Mediterranean", "vegan", "healthy", "casual"],
        hours=_h(),
    ),

    # --- Additional cities: Fremont, Sunnyvale, Santa Clara, Cupertino ---
    dict(
        name="Fremont Indian Spice",
        cuisine_type="Indian",
        address="37100 Fremont Blvd",
        city="Fremont",
        state="CA",
        zip_code="94536",
        description="South Indian vegetarian thali with fresh sambar, rasam, and coconut chutney.",
        phone="(510) 555-3301",
        price_tier=P2,
        amenities=["Vegetarian options", "Takeout"],
        keywords=["Indian", "vegan", "healthy", "family"],
        hours=_h(),
    ),
    dict(
        name="Sunnyvale Korean Kitchen",
        cuisine_type="Korean",
        address="800 W El Camino Real",
        city="Sunnyvale",
        state="CA",
        zip_code="94087",
        description="Home-style Korean with samgyeopsal, kimchi jjigae, and patbingsu dessert.",
        phone="(408) 555-3302",
        price_tier=P2,
        amenities=["Family-friendly", "Takeout"],
        keywords=["Korean", "sweet", "dessert", "family"],
        hours=_h(),
    ),
    dict(
        name="Santa Clara Pho Bistro",
        cuisine_type="Vietnamese",
        address="1800 El Camino Real",
        city="Santa Clara",
        state="CA",
        zip_code="95050",
        description="Modern Vietnamese bistro: craft pho, lemongrass clams, and Vietnamese coffee.",
        phone="(408) 555-3303",
        price_tier=P2,
        amenities=["Takeout", "WiFi"],
        keywords=["Vietnamese", "pho", "casual", "healthy"],
        hours=_h(),
    ),
    dict(
        name="Cupertino Japanese Garden",
        cuisine_type="Japanese",
        address="20800 Stevens Creek Blvd",
        city="Cupertino",
        state="CA",
        zip_code="95014",
        description="Serene garden setting with bento boxes, sashimi platters, and matcha tiramisu.",
        phone="(408) 555-3304",
        price_tier=P3,
        amenities=["Outdoor Seating", "Reservations", "Parking"],
        keywords=["Japanese", "sushi", "romantic", "healthy", "sweet"],
        hours=_h(),
    ),
    dict(
        name="Mountain View Chinese Bistro",
        cuisine_type="Chinese",
        address="100 Castro St",
        city="Mountain View",
        state="CA",
        zip_code="94041",
        description="Modern Chinese small plates and hand-craft cocktails on Castro Street.",
        phone="(650) 555-3305",
        price_tier=P3,
        amenities=["Bar", "Reservations"],
        keywords=["Chinese", "upscale", "cocktails", "date night"],
        hours=_h(),
    ),
    dict(
        name="Millbrae Mediterranean",
        cuisine_type="Mediterranean",
        address="600 El Camino Real",
        city="Millbrae",
        state="CA",
        zip_code="94030",
        description="Bright family Mediterranean with mixed grill platters and garlic spread.",
        phone="(650) 555-3306",
        price_tier=P2,
        amenities=["Family-friendly", "Patio"],
        keywords=["Mediterranean", "healthy", "family", "casual"],
        hours=_h(),
    ),
    dict(
        name="Burlingame French Quarter",
        cuisine_type="French",
        address="300 Primrose Rd",
        city="Burlingame",
        state="CA",
        zip_code="94010",
        description="Wine-focused French with half-off bottles Tuesdays, steak au poivre, and mousse au chocolat.",
        phone="(650) 555-3307",
        price_tier=P3,
        amenities=["Reservations", "Wine bar", "Romantic"],
        keywords=["French", "romantic", "wine", "sweet", "date night"],
        hours=_h(Monday="Closed"),
    ),
    dict(
        name="Fremont Taqueria Jalisco",
        cuisine_type="Mexican",
        address="3800 Mowry Ave",
        city="Fremont",
        state="CA",
        zip_code="94538",
        description="Authentic Jalisco-style birria tacos, consommé, and horchata.",
        phone="(510) 555-3308",
        price_tier=P1,
        amenities=["Takeout", "Casual"],
        keywords=["Mexican", "cheap eats", "tacos", "family"],
        hours=_h(),
    ),
    dict(
        name="Sunnyvale Italian Kitchen",
        cuisine_type="Italian",
        address="100 W Murphy Ave",
        city="Sunnyvale",
        state="CA",
        zip_code="94086",
        description="Classic Italian red-sauce joint: spaghetti carbonara, chicken parmesan, and tiramisu.",
        phone="(408) 555-3309",
        price_tier=P2,
        amenities=["Family-friendly", "Takeout"],
        keywords=["Italian", "pasta", "sweet", "dessert", "casual"],
        hours=_h(),
    ),
    dict(
        name="Tech Campus Grill",
        cuisine_type="American",
        address="600 Mathilda Ave",
        city="Sunnyvale",
        state="CA",
        zip_code="94086",
        description="Build-your-own bowls, premium burgers, and kombucha on tap. Popular with tech workers.",
        phone="(408) 555-3310",
        price_tier=P2,
        amenities=["WiFi", "Healthy options", "Takeout"],
        keywords=["American", "healthy", "burgers", "casual"],
        hours=_h(Saturday="Closed", Sunday="Closed"),
    ),

    # --- 16 final additions to round out coverage ---
    dict(
        name="Berkeley Pasta Lab",
        cuisine_type="Italian",
        address="2320 Telegraph Ave",
        city="Berkeley",
        state="CA",
        zip_code="94704",
        description="Rotating fresh pasta menus, natural wines, and panna cotta to finish.",
        phone="(510) 555-4001",
        price_tier=P3,
        amenities=["Reservations", "Wine bar"],
        keywords=["Italian", "romantic", "date night", "pasta"],
        hours=_h(Monday="Closed"),
    ),
    dict(
        name="Sichuan Dynasty",
        cuisine_type="Chinese",
        address="1800 Shattuck Ave",
        city="Berkeley",
        state="CA",
        zip_code="94709",
        description="Authentic Sichuan mala hot pot and cold sesame noodles in a vibrant dining room.",
        phone="(510) 555-4002",
        price_tier=P3,
        amenities=["Group-friendly", "Bar"],
        keywords=["Chinese", "spicy", "hot pot", "group"],
        hours=_h(),
    ),
    dict(
        name="Mission Cantina",
        cuisine_type="Mexican",
        address="500 Valencia St",
        city="San Francisco",
        state="CA",
        zip_code="94110",
        description="Modern cantina with wood-fire mezcal cocktails, street-corn flatbreads, and duck carnitas.",
        phone="(415) 555-4003",
        price_tier=P3,
        amenities=["Bar", "Reservations", "Outdoor Seating"],
        keywords=["Mexican", "cocktails", "upscale", "romantic"],
        hours=_h(),
    ),
    dict(
        name="East Bay Pho Co",
        cuisine_type="Vietnamese",
        address="4400 Piedmont Ave",
        city="Oakland",
        state="CA",
        zip_code="94611",
        description="Rich beef pho and lemongrass chicken with fresh herb plates.",
        phone="(510) 555-4004",
        price_tier=P3,
        amenities=["Reservations", "Full bar"],
        keywords=["Vietnamese", "pho", "romantic", "date night"],
        hours=_h(),
    ),
    dict(
        name="Gangnam Seoul",
        cuisine_type="Korean",
        address="700 Post St",
        city="San Francisco",
        state="CA",
        zip_code="94109",
        description="Upscale Korean with premium galbi, wagyu tartare, and Korean rice wine pairings.",
        phone="(415) 555-4005",
        price_tier=P3,
        amenities=["Bar", "Reservations", "Romantic"],
        keywords=["Korean", "upscale", "date night", "fine dining"],
        hours=_h(Monday="Closed"),
    ),
    dict(
        name="Palo Alto Sushi",
        cuisine_type="Japanese",
        address="412 University Ave",
        city="Palo Alto",
        state="CA",
        zip_code="94301",
        description="Premium sushi counter with seasonal fish and Japanese whisky flights.",
        phone="(650) 555-4006",
        price_tier=P3,
        amenities=["Reservations", "Bar"],
        keywords=["sushi", "Japanese", "date night", "romantic"],
        hours=_h(Monday="Closed"),
    ),
    dict(
        name="Tandoor Palace Oakland",
        cuisine_type="Indian",
        address="5100 Broadway",
        city="Oakland",
        state="CA",
        zip_code="94611",
        description="Elevated Indian fine dining with slow-cooked dum biryani and saffron kulfi.",
        phone="(510) 555-4007",
        price_tier=P4,
        amenities=["Fine dining", "Reservations", "Full bar"],
        keywords=["Indian", "fine dining", "romantic", "special occasion"],
        hours=_h(Monday="Closed"),
    ),
    dict(
        name="Berkeley Farmhouse",
        cuisine_type="American",
        address="1450 University Ave",
        city="Berkeley",
        state="CA",
        zip_code="94702",
        description="Rustic farm-to-table with wood-fired chicken, heirloom salads, and whisky tasting.",
        phone="(510) 555-4008",
        price_tier=P3,
        amenities=["Bar", "Reservations", "Outdoor Seating"],
        keywords=["American", "farm-to-table", "romantic", "date night"],
        hours=_h(),
    ),
    dict(
        name="Thai Lotus Blossom",
        cuisine_type="Thai",
        address="2400 Telegraph Ave",
        city="Berkeley",
        state="CA",
        zip_code="94704",
        description="Quick Thai counter with red and green curries, papaya salad, and bubble tea.",
        phone="(510) 555-4009",
        price_tier=P1,
        amenities=["Takeout", "Delivery", "Casual"],
        keywords=["Thai", "cheap eats", "spicy", "sweet"],
        hours=_h(),
    ),
    dict(
        name="Embarcadero Med Kitchen",
        cuisine_type="Mediterranean",
        address="1 Embarcadero Center",
        city="San Francisco",
        state="CA",
        zip_code="94111",
        description="Upscale mezze and wine bar overlooking the Embarcadero with Moroccan lamb chops.",
        phone="(415) 555-4010",
        price_tier=P3,
        amenities=["Wine bar", "View", "Reservations"],
        keywords=["Mediterranean", "romantic", "view", "date night"],
        hours=_h(),
    ),
    dict(
        name="Le Coin",
        cuisine_type="French",
        address="50 Maiden Lane",
        city="San Francisco",
        state="CA",
        zip_code="94108",
        description="Tiny, charming French corner café with formidable crêpes and vin chaud.",
        phone="(415) 555-4011",
        price_tier=P1,
        amenities=["Coffee", "Takeout", "Casual"],
        keywords=["French", "sweet", "brunch", "cheap eats", "pastries"],
        hours=_h(Saturday="9am-5pm", Sunday="Closed"),
    ),
    dict(
        name="Olive & Fig",
        cuisine_type="Greek",
        address="2800 MacArthur Blvd",
        city="Oakland",
        state="CA",
        zip_code="94602",
        description="BYOB Greek with spanakopita, grilled halloumi, and baklava sundaes.",
        phone="(510) 555-4012",
        price_tier=P1,
        amenities=["BYOB", "Family-friendly", "Takeout"],
        keywords=["Greek", "cheap eats", "sweet", "family"],
        hours=_h(),
    ),
    dict(
        name="Grand Palace Cantonese",
        cuisine_type="Chinese",
        address="838 Grant Ave",
        city="San Francisco",
        state="CA",
        zip_code="94108",
        description="Elegant Cantonese banquet dining: bird's nest soup, lobster noodles, and mango pudding.",
        phone="(415) 555-4013",
        price_tier=P4,
        amenities=["Fine dining", "Private dining", "Banquet"],
        keywords=["Chinese", "fine dining", "special occasion", "upscale"],
        hours=_h(),
    ),
    dict(
        name="Trattoria da Marco",
        cuisine_type="Italian",
        address="780 N 1st St",
        city="San Jose",
        state="CA",
        zip_code="95112",
        description="Affordable Italian classics: margherita pizza, garlic bread, and gelato.",
        phone="(408) 555-4014",
        price_tier=P1,
        amenities=["Takeout", "Family-friendly"],
        keywords=["Italian", "pizza", "cheap eats", "casual"],
        hours=_h(),
    ),
    dict(
        name="Cocina Guadalajara",
        cuisine_type="Mexican",
        address="1800 San Pablo Ave",
        city="Berkeley",
        state="CA",
        zip_code="94702",
        description="Family-run Mexican with authentic posole, enchiladas verdes, and flan.",
        phone="(510) 555-4015",
        price_tier=P2,
        amenities=["Family-friendly", "Takeout"],
        keywords=["Mexican", "sweet", "dessert", "family", "casual"],
        hours=_h(),
    ),
    dict(
        name="Hoi An Garden",
        cuisine_type="Vietnamese",
        address="2500 College Ave",
        city="Berkeley",
        state="CA",
        zip_code="94704",
        description="Garden patio Vietnamese with cao lau noodles, prawn spring rolls, and che ba mau.",
        phone="(510) 555-4016",
        price_tier=P3,
        amenities=["Outdoor Seating", "Reservations", "Romantic"],
        keywords=["Vietnamese", "romantic", "sweet", "view"],
        hours=_h(),
    ),
]

assert len(RESTAURANTS) == 150, len(RESTAURANTS)


def main() -> None:
    """Append missing restaurants (requires at least one user, e.g. alice@example.com)."""
    import sys
    import os

    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

    from sqlalchemy import func
    from database import SessionLocal

    db = SessionLocal()
    try:
        user = db.query(models.User).filter(models.User.email == "alice@example.com").first()
        if not user:
            print("No user found. Create a user first or run seed.py on a fresh database.")
            sys.exit(1)

        existing_names = {r.name for r in db.query(models.Restaurant).all()}
        added = 0
        for data in RESTAURANTS:
            if data["name"] in existing_names:
                continue
            db.add(models.Restaurant(**data, added_by=user.id))
            added += 1

        db.commit()
        print(f"✅ Added {added} new restaurants (skipped {len(RESTAURANTS) - added} already present).")

        if added:
            for r in db.query(models.Restaurant).all():
                result = (
                    db.query(func.avg(models.Review.rating), func.count(models.Review.id))
                    .filter(models.Review.restaurant_id == r.id)
                    .first()
                )
                r.average_rating = round(float(result[0] or 0), 2)
                r.review_count = result[1] or 0
            db.commit()
            print("   Recalculated average_rating / review_count for all restaurants.")

    except Exception as e:
        db.rollback()
        print(f"❌ Error: {e}")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    main()
