"""
50 diverse demo restaurants + script to append missing rows to an existing DB.

- `from seed_restaurants import RESTAURANTS` — used by seed.py on a fresh database.
- Run: `python seed_restaurants.py` — adds any restaurants from RESTAURANTS whose
  names are not already in the database (keeps your existing data).
"""

import models

_DEFAULT_HOURS = {
    "Monday": "11am-10pm",
    "Tuesday": "11am-10pm",
    "Wednesday": "11am-10pm",
    "Thursday": "11am-10pm",
    "Friday": "11am-11pm",
    "Saturday": "10am-11pm",
    "Sunday": "10am-9pm",
}

P1, P2, P3, P4 = (
    models.PriceTier.one,
    models.PriceTier.two,
    models.PriceTier.three,
    models.PriceTier.four,
)


def _h(**kwargs):
    return {**_DEFAULT_HOURS, **kwargs}


# ── 50 restaurants: varied cuisines, cities, price, keywords for AI / search ──
RESTAURANTS = [
    # --- Italian & Mediterranean ---
    dict(
        name="Tony's Little Italy",
        cuisine_type="Italian",
        address="1800 Washington St",
        city="San Francisco",
        state="CA",
        zip_code="94109",
        description="Authentic Italian cuisine with homemade pasta and a cozy atmosphere. Family-owned since 1987.",
        phone="(415) 555-0101",
        price_tier=P2,
        amenities=["WiFi", "Reservations", "Family-friendly"],
        keywords=["pasta", "pizza", "romantic", "wine"],
        hours=_h(),
    ),
    dict(
        name="Osteria Luna",
        cuisine_type="Italian",
        address="244 Valencia St",
        city="San Francisco",
        state="CA",
        zip_code="94103",
        description="Candlelit tables, handmade gnocchi, and an all-Italian wine list. Ideal for anniversaries.",
        phone="(415) 555-0102",
        price_tier=P3,
        amenities=["Reservations", "Wine bar", "Romantic"],
        keywords=["romantic", "fine dining", "date night", "upscale"],
        hours=_h(),
    ),
    dict(
        name="Mare Blu",
        cuisine_type="Mediterranean",
        address="900 North Point St",
        city="San Francisco",
        state="CA",
        zip_code="94109",
        description="Seafood-forward Mediterranean plates with harbor views and grilled octopus.",
        phone="(415) 555-0103",
        price_tier=P3,
        amenities=["Waterfront", "Reservations", "Full bar"],
        keywords=["seafood", "romantic", "view", "fine dining"],
        hours=_h(),
    ),
    # --- Mexican & Latin ---
    dict(
        name="El Farolito",
        cuisine_type="Mexican",
        address="2779 Mission St",
        city="San Francisco",
        state="CA",
        zip_code="94110",
        description="Late-night Mission District taqueria famous for oversized burritos and street tacos.",
        phone="(415) 555-0201",
        price_tier=P1,
        amenities=["Takeout", "Family-friendly"],
        keywords=["tacos", "burritos", "late night", "cheap eats"],
        hours=_h(Friday="10am-3am", Saturday="10am-3am"),
    ),
    dict(
        name="Cielito Lindo Plantas",
        cuisine_type="Mexican",
        address="3120 24th St",
        city="San Francisco",
        state="CA",
        zip_code="94110",
        description="Plant-based Mexican kitchen: jackfruit carnitas, cashew queso, and vegan tres leches for dessert.",
        phone="(415) 555-0202",
        price_tier=P2,
        amenities=["Vegan", "Outdoor Seating", "Takeout"],
        keywords=["vegan", "Mexican", "sweet", "dessert", "gluten-free"],
        hours=_h(),
    ),
    dict(
        name="Café de Olla",
        cuisine_type="Mexican",
        address="1800 Polk St",
        city="San Francisco",
        state="CA",
        zip_code="94109",
        description="Traditional mole, café de olla, and churros with chocolate dipping sauce.",
        phone="(415) 555-0203",
        price_tier=P2,
        amenities=["Brunch", "Coffee", "Dessert"],
        keywords=["sweet", "dessert", "coffee", "romantic", "brunch"],
        hours=_h(Saturday="9am-10pm", Sunday="9am-9pm"),
    ),
    # --- Asian ---
    dict(
        name="Dragon Palace",
        cuisine_type="Chinese",
        address="640 Jackson St",
        city="San Francisco",
        state="CA",
        zip_code="94133",
        description="Traditional Cantonese dim sum and seafood. Chinatown institution for over 30 years.",
        phone="(415) 555-0301",
        price_tier=P2,
        amenities=["Takeout", "Family-friendly", "Parking"],
        keywords=["dim sum", "seafood", "family"],
        hours=_h(),
    ),
    dict(
        name="Sakura Sushi",
        cuisine_type="Japanese",
        address="2001 Union St",
        city="San Francisco",
        state="CA",
        zip_code="94123",
        description="Premium omakase and à la carte sushi. Fresh fish flown in daily.",
        phone="(415) 555-0302",
        price_tier=P3,
        amenities=["Reservations", "Bar", "WiFi"],
        keywords=["sushi", "omakase", "date night", "fine dining"],
        hours=_h(Monday="Closed"),
    ),
    dict(
        name="Kin Khao",
        cuisine_type="Thai",
        address="55 Cyril Magnin St",
        city="San Francisco",
        state="CA",
        zip_code="94102",
        description="Bold Thai flavors, spicy curries, and mango sticky rice for a sweet finish.",
        phone="(415) 555-0303",
        price_tier=P2,
        amenities=["Takeout", "Spicy", "Dessert"],
        keywords=["Thai", "sweet", "spicy", "casual"],
        hours=_h(),
    ),
    dict(
        name="Lotus Leaf Vietnamese",
        cuisine_type="Vietnamese",
        address="731 Larkin St",
        city="San Francisco",
        state="CA",
        zip_code="94109",
        description="Pho, banh mi, and fresh herb plates. Light, bright space.",
        phone="(415) 555-0304",
        price_tier=P1,
        amenities=["Takeout", "Casual"],
        keywords=["pho", "healthy", "cheap eats"],
        hours=_h(),
    ),
    dict(
        name="Seoul Kitchen",
        cuisine_type="Korean",
        address="2200 Irving St",
        city="San Francisco",
        state="CA",
        zip_code="94122",
        description="Korean BBQ at the table, banchan parade, and soju cocktails.",
        phone="(415) 555-0305",
        price_tier=P2,
        amenities=["BBQ tables", "Bar", "Group-friendly"],
        keywords=["Korean BBQ", "late night", "fun"],
        hours=_h(),
    ),
    dict(
        name="Spice Route India",
        cuisine_type="Indian",
        address="1634 Haight St",
        city="San Francisco",
        state="CA",
        zip_code="94117",
        description="Regional curries, tandoor breads, and vegan thali nights every Thursday.",
        phone="(415) 555-0306",
        price_tier=P2,
        amenities=["Vegetarian options", "Reservations"],
        keywords=["Indian", "vegan", "spicy", "family"],
        hours=_h(),
    ),
    # --- American & brunch ---
    dict(
        name="Fog City Diner",
        cuisine_type="American",
        address="1300 Battery St",
        city="San Francisco",
        state="CA",
        zip_code="94111",
        description="Classic diner with burgers, shakes, and all-day breakfast.",
        phone="(415) 555-0401",
        price_tier=P2,
        amenities=["Bar", "Family-friendly", "WiFi"],
        keywords=["burgers", "brunch", "sweet", "milkshakes", "comfort food"],
        hours=_h(),
    ),
    dict(
        name="Nopa",
        cuisine_type="American",
        address="560 Divisadero St",
        city="San Francisco",
        state="CA",
        zip_code="94117",
        description="Farm-to-table in a stunning space. Cocktails and wood-fired dishes.",
        phone="(415) 555-0402",
        price_tier=P3,
        amenities=["Bar", "Reservations", "Outdoor Seating"],
        keywords=["farm-to-table", "cocktails", "date night", "upscale"],
        hours=_h(),
    ),
    dict(
        name="Ember & Oak Steakhouse",
        cuisine_type="American",
        address="252 California St",
        city="San Francisco",
        state="CA",
        zip_code="94111",
        description="Dry-aged steaks, truffle sides, and a deep wine cellar. Jacket-friendly fine dining.",
        phone="(415) 555-0403",
        price_tier=P4,
        amenities=["Fine dining", "Private dining", "Wine cellar"],
        keywords=["fine dining", "romantic", "steakhouse", "special occasion"],
        hours=_h(Sunday="5pm-10pm"),
    ),
    # --- Vegan & healthy ---
    dict(
        name="The Green Bowl",
        cuisine_type="Vegan",
        address="525 Hayes St",
        city="San Francisco",
        state="CA",
        zip_code="94102",
        description="100% plant-based bowls, smoothies, and seasonal specials.",
        phone="(415) 555-0501",
        price_tier=P2,
        amenities=["WiFi", "Takeout", "Delivery", "Outdoor Seating"],
        keywords=["vegan", "healthy", "bowls", "gluten-free"],
        hours=_h(),
    ),
    dict(
        name="Roots & Ritual",
        cuisine_type="Vegan",
        address="428 Castro St",
        city="San Francisco",
        state="CA",
        zip_code="94114",
        description="Fine plant-based tasting menus with wine pairings in a minimalist dining room.",
        phone="(415) 555-0502",
        price_tier=P3,
        amenities=["Reservations", "Tasting menu", "Wine"],
        keywords=["vegan", "fine dining", "romantic", "date night"],
        hours=_h(Tuesday="Closed", Wednesday="Closed"),
    ),
    dict(
        name="Sprout & Stone",
        cuisine_type="Vegan",
        address="1150 Ocean Ave",
        city="San Francisco",
        state="CA",
        zip_code="94112",
        description="Casual vegan pizzas, cashew mac, and dairy-free soft serve.",
        phone="(415) 555-0503",
        price_tier=P1,
        amenities=["Takeout", "Family-friendly"],
        keywords=["vegan", "pizza", "sweet", "casual"],
        hours=_h(),
    ),
    # --- Bakery & dessert & sweet ---
    dict(
        name="Tartine Bakery",
        cuisine_type="French",
        address="600 Guerrero St",
        city="San Francisco",
        state="CA",
        zip_code="94110",
        description="World-renowned artisan bakery. Morning buns and croissants.",
        phone="(415) 555-0601",
        price_tier=P2,
        amenities=["Takeout", "Coffee"],
        keywords=["bakery", "bread", "pastries", "sweet", "brunch"],
        hours=_h(Monday="Closed", Tuesday="Closed"),
    ),
    dict(
        name="Sugar & Steam",
        cuisine_type="Dessert",
        address="2015 Fillmore St",
        city="San Francisco",
        state="CA",
        zip_code="94115",
        description="Hot desserts, soufflés, and craft hot chocolate. Cozy booths for two.",
        phone="(415) 555-0602",
        price_tier=P2,
        amenities=["Dessert only", "Romantic"],
        keywords=["sweet", "dessert", "romantic", "date night"],
        hours=_h(),
    ),
    dict(
        name="Midnight Gelato Lab",
        cuisine_type="Dessert",
        address="1455 Market St",
        city="San Francisco",
        state="CA",
        zip_code="94103",
        description="Small-batch gelato, affogatos, and vegan sorbetto flights.",
        phone="(415) 555-0603",
        price_tier=P1,
        amenities=["Late night", "Takeout"],
        keywords=["sweet", "gelato", "vegan", "late night"],
        hours=_h(Friday="noon-midnight", Saturday="noon-midnight"),
    ),
    dict(
        name="Honeycomb Patisserie",
        cuisine_type="Bakery",
        address="88 Spear St",
        city="San Francisco",
        state="CA",
        zip_code="94105",
        description="French pastries, viennoiserie, and custom celebration cakes.",
        phone="(415) 555-0604",
        price_tier=P2,
        amenities=["Catering", "Coffee"],
        keywords=["bakery", "sweet", "pastries", "special occasion"],
        hours=_h(Saturday="8am-6pm", Sunday="8am-4pm"),
    ),
    # --- French & European ---
    dict(
        name="Bistro Lumière",
        cuisine_type="French",
        address="1550 California St",
        city="San Francisco",
        state="CA",
        zip_code="94109",
        description="Classic French bistro with duck confit, crème brûlée, and candlelight.",
        phone="(415) 555-0701",
        price_tier=P3,
        amenities=["Reservations", "Romantic", "Wine"],
        keywords=["French", "romantic", "fine dining", "sweet"],
        hours=_h(),
    ),
    dict(
        name="Trattoria Verdi",
        cuisine_type="Italian",
        address="3200 Sacramento St",
        city="San Francisco",
        state="CA",
        zip_code="94115",
        description="Neighborhood Italian with house-made tiramisu and limoncello.",
        phone="(415) 555-0702",
        price_tier=P2,
        amenities=["Patio", "Family-friendly"],
        keywords=["Italian", "sweet", "dessert", "casual"],
        hours=_h(),
    ),
    # --- Seafood & BBQ ---
    dict(
        name="Harbor Catch",
        cuisine_type="Seafood",
        address="Pier 39",
        city="San Francisco",
        state="CA",
        zip_code="94133",
        description="Oysters, cioppino, and grilled fish with bay views.",
        phone="(415) 555-0801",
        price_tier=P3,
        amenities=["Waterfront", "Tourist-friendly"],
        keywords=["seafood", "romantic", "view", "special occasion"],
        hours=_h(),
    ),
    dict(
        name="Low & Slow BBQ",
        cuisine_type="BBQ",
        address="4500 3rd St",
        city="San Francisco",
        state="CA",
        zip_code="94124",
        description="Central Texas-style brisket, smoky ribs, and bourbon cocktails.",
        phone="(415) 555-0802",
        price_tier=P2,
        amenities=["Outdoor seating", "Family-friendly"],
        keywords=["BBQ", "comfort food", "casual"],
        hours=_h(),
    ),
    # --- Ethiopian, Spanish, Greek ---
    dict(
        name="Blue Nile Ethiopian",
        cuisine_type="Ethiopian",
        address="3030 Telegraph Ave",
        city="Berkeley",
        state="CA",
        zip_code="94705",
        description="Injera platters, vegan wot stews, and honey wine.",
        phone="(510) 555-0901",
        price_tier=P2,
        amenities=["Vegetarian friendly", "Share plates"],
        keywords=["Ethiopian", "vegan", "spicy", "family"],
        hours=_h(),
    ),
    dict(
        name="Barcelona Tapas",
        cuisine_type="Spanish",
        address="2020 Shattuck Ave",
        city="Berkeley",
        state="CA",
        zip_code="94704",
        description="Patatas bravas, jamón, and churros with chocolate in a lively room.",
        phone="(510) 555-0902",
        price_tier=P2,
        amenities=["Bar", "Small plates"],
        keywords=["tapas", "romantic", "sweet", "wine"],
        hours=_h(),
    ),
    dict(
        name="Athens Table",
        cuisine_type="Greek",
        address="2500 Durant Ave",
        city="Berkeley",
        state="CA",
        zip_code="94704",
        description="Grilled octopus, lamb chops, and honey yogurt with walnuts.",
        phone="(510) 555-0903",
        price_tier=P2,
        amenities=["Patio", "Family-friendly"],
        keywords=["Greek", "Mediterranean", "sweet", "healthy"],
        hours=_h(),
    ),
    # --- Oakland ---
    dict(
        name="Jack London Grill",
        cuisine_type="American",
        address="66 Franklin St",
        city="Oakland",
        state="CA",
        zip_code="94607",
        description="Waterfront steaks and cocktails near the ferry.",
        phone="(510) 555-1001",
        price_tier=P3,
        amenities=["Bar", "View"],
        keywords=["American", "romantic", "fine dining", "date night"],
        hours=_h(),
    ),
    dict(
        name="Temescal Pizza Co",
        cuisine_type="Italian",
        address="4800 Telegraph Ave",
        city="Oakland",
        state="CA",
        zip_code="94609",
        description="Wood-fired Neapolitan pies and burrata starters.",
        phone="(510) 555-1002",
        price_tier=P2,
        amenities=["Family-friendly", "Beer"],
        keywords=["pizza", "casual", "Italian"],
        hours=_h(),
    ),
    dict(
        name="Lake Chalet Sushi",
        cuisine_type="Japanese",
        address="1520 Lakeside Dr",
        city="Oakland",
        state="CA",
        zip_code="94612",
        description="Sushi and rolls with Lake Merritt views at sunset.",
        phone="(510) 555-1003",
        price_tier=P3,
        amenities=["Reservations", "View"],
        keywords=["sushi", "romantic", "date night", "fine dining"],
        hours=_h(),
    ),
    dict(
        name="Oakland Vegan Deli",
        cuisine_type="Vegan",
        address="1433 Peralta St",
        city="Oakland",
        state="CA",
        zip_code="94607",
        description="Sandwiches, salads, and vegan cookies baked daily.",
        phone="(510) 555-1004",
        price_tier=P1,
        amenities=["Takeout", "Lunch"],
        keywords=["vegan", "sweet", "healthy", "casual"],
        hours=_h(Saturday="Closed", Sunday="Closed"),
    ),
    dict(
        name="Smoky Soul BBQ Oakland",
        cuisine_type="BBQ",
        address="301 Broadway",
        city="Oakland",
        state="CA",
        zip_code="94607",
        description="Brisket, links, and banana pudding for dessert.",
        phone="(510) 555-1005",
        price_tier=P2,
        amenities=["Takeout", "Casual"],
        keywords=["BBQ", "sweet", "comfort food"],
        hours=_h(),
    ),
    # --- San Jose ---
    dict(
        name="Santana Row Brasserie",
        cuisine_type="French",
        city="San Jose",
        state="CA",
        zip_code="95128",
        address="377 Santana Row",
        description="Open-air brasserie with steak frites and crêpes suzette.",
        phone="(408) 555-1101",
        price_tier=P3,
        amenities=["Outdoor seating", "Shopping district"],
        keywords=["French", "romantic", "sweet", "fine dining"],
        hours=_h(),
    ),
    dict(
        name="Little Saigon House",
        cuisine_type="Vietnamese",
        address="1180 Story Rd",
        city="San Jose",
        state="CA",
        zip_code="95122",
        description="Pho, bun cha, and che sweet dessert soups.",
        phone="(408) 555-1102",
        price_tier=P1,
        amenities=["Takeout", "Casual"],
        keywords=["Vietnamese", "sweet", "cheap eats"],
        hours=_h(),
    ),
    dict(
        name="Silicon Tandoor",
        cuisine_type="Indian",
        address="98 S Almaden Blvd",
        city="San Jose",
        state="CA",
        zip_code="95113",
        description="Silicon Valley lunch buffet and refined dinner service.",
        phone="(408) 555-1103",
        price_tier=P2,
        amenities=["Buffet", "Delivery"],
        keywords=["Indian", "spicy", "vegan options", "family"],
        hours=_h(),
    ),
    dict(
        name="Rose Garden Izakaya",
        cuisine_type="Japanese",
        address="367 E Taylor St",
        city="San Jose",
        state="CA",
        zip_code="95112",
        description="Izakaya small plates, yakitori, and sake flights.",
        phone="(408) 555-1104",
        price_tier=P2,
        amenities=["Bar", "Late night"],
        keywords=["Japanese", "date night", "casual"],
        hours=_h(),
    ),
    dict(
        name="Willow Glen Creamery",
        cuisine_type="Dessert",
        address="1155 Lincoln Ave",
        city="San Jose",
        state="CA",
        zip_code="95125",
        description="House-made ice cream, vegan coconut bases, and waffle cones.",
        phone="(408) 555-1105",
        price_tier=P1,
        amenities=["Family-friendly", "Takeout"],
        keywords=["sweet", "dessert", "vegan", "kids"],
        hours=_h(),
    ),
    # --- Palo Alto ---
    dict(
        name="University Avenue Bistro",
        cuisine_type="Mediterranean",
        address="520 University Ave",
        city="Palo Alto",
        state="CA",
        zip_code="94301",
        description="Cal-Mediterranean plates and olive oil cakes for dessert.",
        phone="(650) 555-1201",
        price_tier=P3,
        amenities=["Reservations", "Wine"],
        keywords=["Mediterranean", "romantic", "fine dining", "sweet"],
        hours=_h(),
    ),
    dict(
        name="Palo Alto Bakery Lab",
        cuisine_type="Bakery",
        address="200 California Ave",
        city="Palo Alto",
        state="CA",
        zip_code="94306",
        description="Sourdough experiments, croissants, and seasonal fruit tarts.",
        phone="(650) 555-1202",
        price_tier=P2,
        amenities=["Coffee", "WiFi"],
        keywords=["bakery", "sweet", "brunch", "pastries"],
        hours=_h(),
    ),
    dict(
        name="Nob Hill Gardens",
        cuisine_type="American",
        address="100 University Ave",
        city="Palo Alto",
        state="CA",
        zip_code="94301",
        description="Garden patio, tasting menus, sommelier service — special-occasion dining.",
        phone="(650) 555-1203",
        price_tier=P4,
        amenities=["Fine dining", "Garden", "Private events"],
        keywords=["fine dining", "romantic", "special occasion", "upscale"],
        hours=_h(Monday="Closed", Tuesday="Closed"),
    ),
    # --- More SF variety ---
    dict(
        name="Mission Burritos Express",
        cuisine_type="Mexican",
        address="1700 Mission St",
        city="San Francisco",
        state="CA",
        zip_code="94103",
        description="Fast counter-service burritos and agua frescas.",
        phone="(415) 555-1301",
        price_tier=P1,
        amenities=["Takeout"],
        keywords=["Mexican", "cheap eats", "late night"],
        hours=_h(),
    ),
    dict(
        name="Nob Hill Supper Club",
        cuisine_type="American",
        address="1000 California St",
        city="San Francisco",
        state="CA",
        zip_code="94108",
        description="Jazz brunch and prix-fixe dinners in a historic hotel dining room.",
        phone="(415) 555-1302",
        price_tier=P4,
        amenities=["Live music", "Fine dining", "Reservations"],
        keywords=["fine dining", "romantic", "jazz", "special occasion"],
        hours=_h(),
    ),
    dict(
        name="Sunset Ramen House",
        cuisine_type="Japanese",
        address="1730 Irving St",
        city="San Francisco",
        state="CA",
        zip_code="94122",
        description="Rich tonkotsu, vegan miso ramen, and matcha desserts.",
        phone="(415) 555-1303",
        price_tier=P2,
        amenities=["Counter seating", "Takeout"],
        keywords=["ramen", "vegan", "sweet", "casual"],
        hours=_h(),
    ),
    dict(
        name="Castro Creperie",
        cuisine_type="French",
        address="389 Castro St",
        city="San Francisco",
        state="CA",
        zip_code="94114",
        description="Sweet and savory crêpes, Nutella specials, and cider.",
        phone="(415) 555-1304",
        price_tier=P1,
        amenities=["Outdoor seating", "Casual"],
        keywords=["sweet", "dessert", "romantic", "brunch"],
        hours=_h(),
    ),
    dict(
        name="Richmond Thai House",
        cuisine_type="Thai",
        address="602 Clement St",
        city="San Francisco",
        state="CA",
        zip_code="94118",
        description="Regional Thai curries, mango rice, and herbal salads.",
        phone="(415) 555-1305",
        price_tier=P2,
        amenities=["Takeout", "Spicy"],
        keywords=["Thai", "sweet", "spicy", "family"],
        hours=_h(),
    ),
    dict(
        name="SoMa Wine Kitchen",
        cuisine_type="Mediterranean",
        address="555 2nd St",
        city="San Francisco",
        state="CA",
        zip_code="94107",
        description="Wine flights, charcuterie, and chocolate torte pairings.",
        phone="(415) 555-1307",
        price_tier=P3,
        amenities=["Wine bar", "Reservations"],
        keywords=["romantic", "wine", "sweet", "date night"],
        hours=_h(),
    ),
    dict(
        name="Bernal Heights Taqueria",
        cuisine_type="Mexican",
        address="900 Cortland Ave",
        city="San Francisco",
        state="CA",
        zip_code="94110",
        description="Neighborhood taqueria with excellent salsa bar and flan.",
        phone="(415) 555-1308",
        price_tier=P1,
        amenities=["Takeout", "Casual"],
        keywords=["Mexican", "sweet", "dessert", "family"],
        hours=_h(),
    ),
    dict(
        name="Hayes Valley Brasserie",
        cuisine_type="French",
        address="450 Hayes St",
        city="San Francisco",
        state="CA",
        zip_code="94102",
        description="Bistro classics, natural wines, and romantic sidewalk seating.",
        phone="(415) 555-1310",
        price_tier=P3,
        amenities=["Reservations", "Romantic", "Patio"],
        keywords=["French", "romantic", "fine dining", "date night"],
        hours=_h(),
    ),
]

assert len(RESTAURANTS) == 50, len(RESTAURANTS)


def main() -> None:
    """Append missing restaurants (requires at least one user, e.g. alice@example.com)."""
    import sys
    import os

    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

    from sqlalchemy import func
    from database import SessionLocal

    db = SessionLocal()
    try:
        user = db.query(models.User).filter(models.User.email == "alice@example.com").first()
        if not user:
            print("No user found. Create a user first or run seed.py on a fresh database.")
            sys.exit(1)

        existing_names = {r.name for r in db.query(models.Restaurant).all()}
        added = 0
        for data in RESTAURANTS:
            if data["name"] in existing_names:
                continue
            db.add(models.Restaurant(**data, added_by=user.id))
            added += 1

        db.commit()
        print(f"✅ Added {added} new restaurants (skipped {len(RESTAURANTS) - added} already present).")

        if added:
            for r in db.query(models.Restaurant).all():
                result = (
                    db.query(func.avg(models.Review.rating), func.count(models.Review.id))
                    .filter(models.Review.restaurant_id == r.id)
                    .first()
                )
                r.average_rating = round(float(result[0] or 0), 2)
                r.review_count = result[1] or 0
            db.commit()
            print("   Recalculated average_rating / review_count for all restaurants.")

    except Exception as e:
        db.rollback()
        print(f"❌ Error: {e}")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    main()
