apiVersion: v1
kind: ConfigMap
metadata:
  name: yelp-lab2-config
  namespace: yelp-lab2
data:
  MONGODB_URL: mongodb://mongodb:27017
  MONGODB_DB: yelp_lab2
  JWT_ALGORITHM: HS256
  SESSION_EXPIRE_MINUTES: "1440"
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  KAFKA_CLIENT_ID: yelp-lab2
